### ISSUE TITLE
Artipie docker image artipie/artipie:v0.27.7 may fail to start due to several asto jar files with different versions.

### ISSUE THREAD

**Issue by ChGen** [artipie/artipie#1210]
Artipie docker image `artipie/artipie:v0.27.7` may fail to start due to several asto jar files with different versions.
Artipie builds with multiple adapters as dependencies, and artipie asto versions differ among them. Also they are referenced in `pom.xml` both, as `asto` and `asto-core`. So after `artipie/artipie` is built it may fail to start due to several asto jar files with unpredictable loading order.
Example is given below. 
Also, direct update of all dependencies requires fixing update issues in adapters: `gem-adapter`, `go-adapter`.
Adapter issues:
https://github.com/artipie/go-adapter/issues/143
https://github.com/artipie/gem-adapter/issues/216

Example:
```
 ls -l target/dependency/|grep -i asto
-rw-r--r-- 1 evgeny evgeny   144576 Dec  5 10:05 asto-core-v1.15.1.jar
-rw-r--r-- 1 evgeny evgeny   152122 Oct  7 12:58 asto-v1.11.0.jar
```

Startup exception:
```
docker run -it artipie/artipie:v0.27.7 

...................
Exception in thread "main" com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: 'java.lang.String com.artipie.asto.Storage.identifier()'
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4848)
        at com.artipie.settings.cache.CachedStorages.storage(CachedStorages.java:72)
        at com.artipie.settings.cache.CachedStorages.storage(CachedStorages.java:66)
        at com.artipie.settings.YamlSettings.configStorage(YamlSettings.java:81)
        at com.artipie.settings.SettingsFromPath.find(SettingsFromPath.java:55)
        at com.artipie.VertxMain.start(VertxMain.java:111)
        at com.artipie.VertxMain.main(VertxMain.java:184)
Caused by: java.lang.NoSuchMethodError: 'java.lang.String com.artipie.asto.Storage.identifier()'
        at com.artipie.settings.cache.CachedStorages.lambda$storage$0(CachedStorages.java:86)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4853)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
        ... 8 more
...................
```

Now I use test image, with all adapters updated manually to the latest `asto-core` with skipped tests `chgena/artipie:bc37982.1`

**Comment by ChGen** [comment]
Experimental branch for asto-core with skipped tests chgena/artipie:bc37982.1:https://github.com/artipie/artipie/tree/ech-asto-deps
