### ISSUE TITLE
Issue: Artipie checks dotfiles when loading yaml/yml files

### ISSUE THREAD

**Issue by CodeRemovalTechnician** [artipie/artipie#1241]
Hi Team,

**Artipie version**: Docker image v0.28.0
**Platform**: Kubernetes (K3S) v1.26.1 on Windows 11 

After successfully experimenting with docker-compose I wanted to test running Artipie on a local Kubernetes cluster using the file storage backend. I created a custom Helm chart with the following additional templates:

- a ConfigMap for the artipie.yml configuration file,
- a ConfigMap for the _storages.yaml file,
- a Secret for _credentials file.

These configuration files are then mounted in the Artipie pod as follows:

```
containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.http.targetPort }}
              protocol: TCP
            - name: swagger
              containerPort: {{ .Values.service.api.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /.health
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: main
              mountPath: "{{ .Values.artipie.config_dir }}"
            - name: artipie-data
              mountPath: "{{ .Values.artipie.data_dir }}"
            - name: configs
              mountPath: "{{ .Values.artipie.data_dir }}/configs"
            - name: repos
              mountPath: "{{ .Values.artipie.data_dir }}/configs/{{ .Values.artipie.default_org }}"
      volumes:
        # main configuration file for Docker
        - name: main
          configMap:
            name: artipie
            items:
              - key: "artipie"
                path: "artipie.yml"
        # artifacts storage root directory
        - name: artipie-data
          hostPath:
            path: "/<localFolder>/data"
            type: Directory
        # Additional config files
        - name: configs
          projected:
            sources:
              # Storage aliases (per repo configuration)
              - configMap:
                  name: storages
                  items:
                    - key: "storages"
                      path: "_storages.yaml"
              # default user credentials
              - secret:
                  name: credentials
                  items:
                    - key: "credentials"
                      path: "_credentials.yaml"
                  optional: false
```
This caused an issue when starting Artipie because it analyzed hidden folders/files creating for bind mounting the ConfigMaps and Secrets:

```
 〉kubectl logs -n artipie artipie-84c4d5bd5-vlp6r                                                                                                                 Mon Feb  6 10:57:25 2023
[main] INFO com.artipie.VertxMain - Used version of Artipie: v0.28.0
[main] INFO org.eclipse.jetty.util.log - Logging initialized @3397ms to org.eclipse.jetty.util.log.Slf4jLog
[main] INFO org.reflections.Reflections - Reflections took 996 ms to scan 1 urls, producing 36 keys and 78 values
[main] INFO com.artipie.asto.factory.Storages - Initiated storage factory [type=fs, class=FileStorageFactory]
[main] INFO com.artipie.VertxMain - Artipie was started on port 8080
[Thread-10] INFO com.artipie.asto.fs.FileStorage - Found 24 objects by the prefix "" in /var/artipie/configs by /var/artipie/configs: [..2023_02_06_09_57_10.2284382907/_credentials.yaml, ..2023_02_06_09_57_10.2284382907/_storages.yaml, _credentials.yaml, _storages.yaml, private/..2023_02_06_09_57_10.3087496895/binaries.yaml, private/..2023_02_06_09_57_10.3087496895/docker-remote.yaml, private/..2023_02_06_09_57_10.3087496895/docker.yaml, private/..2023_02_06_09_57_10.3087496895/helm.yaml, private/..2023_02_06_09_57_10.3087496895/maven-remote.yaml, private/..2023_0Exception in thread "main" java.util.concurrent.CompletionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Filename `..2023_02_06_09        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:653)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Filename `..2023_02_06_09_57_10` should have `.yaml` or `.yml` extension or be without extension
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4941)
        at com.artipie.settings.repo.RepositoriesFromStorage.config(RepositoriesFromStorage.java:99)
        at com.artipie.VertxMain.lambda$startRepos$1(VertxMain.java:206)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.artipie.VertxMain.lambda$startRepos$3(VertxMain.java:208)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        ... 5 more
Caused by: java.lang.IllegalStateException: Filename `..2023_02_06_09_57_10` should have `.yaml` or `.yml` extension or be without extension
        at com.artipie.settings.ConfigFile.valueFrom(ConfigFile.java:123)
        at com.artipie.settings.repo.RepositoriesFromStorage$FilesContent.configContent(RepositoriesFromStorage.java:162)
        at com.artipie.settings.repo.RepositoriesFromStorage$1.load(RepositoriesFromStorage.java:55)
        at com.artipie.settings.repo.RepositoriesFromStorage$1.load(RepositoriesFromStorage.java:52)
```

Would it be possible to ignore dotfiles to prevent thees kind of issues ?

**Comment by olenagerasimova** [comment]
hi @CodeRemovalTechnician , thanks for reporting the issue! We are considering the problem, for now I can suggest you to put all the repository configurations into separate folder (subfolder of the config storage specified in artipie.yml) and specify it in the `configs` yaml node in the `artipie.yml`. In this case artipie will scan only this folder for repository configurations:
```yaml
# artipie.yml
meta:
  storage: # config storage
    type: fs
    path: /tmp/artipie/configs
  configs: repo # subfolder in /tmp/artipie/configs with repo configs
  ...
```
Check [wiki](https://github.com/artipie/artipie/wiki/Configuration) for more details and do not hesitate to report more issues or ask questions!

**Comment by CodeRemovalTechnician** [comment]
Hi @olenagerasimova ,

Thanks for the suggestion. I did gave it a try:

````
apiVersion: v1
kind: ConfigMap
metadata:
  name: artipie
data:
  artipie: |
    meta:
      layout: org
      configs: repos
      credentials:
        - type: file
          path: _credentials.yaml
      storage:
        type: fs
        path: "{{ .Values.artipie.data_dir }}/configs"
````
and mounted the configMaps for the repositories in the _/repos_ subfolder:

```
...
 volumeMounts:
            - name: main
              mountPath: "{{ .Values.artipie.config_dir }}"
            - name: artipie-data
              mountPath: "{{ .Values.artipie.data_dir }}"
            - name: configs
              mountPath: "{{ .Values.artipie.data_dir }}/configs"
            - name: repos
              mountPath: "{{ .Values.artipie.data_dir }}/configs/repos/{{ .Values.artipie.default_org }}"
```
Unfortunately, it did not solve my issue (same error, same stacktrace) as Artipie still tries to parse files in hidden folders. I can try mounting an entire volume with the current configuration files  in the pod to avoid mounting individual files but that goes against my goal to manage the configuration as Kubernetes objects.

**Comment by ChGen** [comment]
@CodeRemovalTechnician , in order to have better understanding of the case, what kind of hidden directories are stored in the "{{ .Values.artipie.data_dir }}/configs" directory? (Like, is it some service data for kubernetes helm, or manual artipie configurations backups?)

**Comment by CodeRemovalTechnician** [comment]
@olenagerasimova 

I should have started by showing what is the file structure created in _/var/artipie/configs_ to clarify the issue. My bad.
Here is what is actually been mounted in Artipie:

```
 〉kubectl exec -it -n artipie artipie-59cccd586c-6txnw -- ls -la /var/artipie/configs                                                                        Tue Feb  7 16:55:09 2023 羽 3stotal 0
drwxrwxrwt 4 root root  140 Feb  7 15:54 .
drwxrwxrwx 1 root root 4096 Feb  6 09:35 ..
drwxr-xr-x 2 root root   80 Feb  7 15:54 ..2023_02_07_15_54_11.3145060576
lrwxrwxrwx 1 root root   32 Feb  7 15:54 ..data -> ..2023_02_07_15_54_11.3145060576
lrwxrwxrwx 1 root root   24 Feb  7 15:54 _credentials.yaml -> ..data/_credentials.yaml
lrwxrwxrwx 1 root root   21 Feb  7 15:54 _storages.yaml -> ..data/_storages.yaml
drwxr-xr-x 3 root root   60 Feb  7 15:54 repos
```

**Comment by olenagerasimova** [comment]
@CodeRemovalTechnician thanks for the details, though I do not fully understand why `..2023_02_07_15_54_11.3145060576` folder is required in the config directory...

We discussed the issue and decided not to exclude hidden files, as configuration storage is a general storage (it can be s3 or some other storage). Also, we do not expect users to store any other files in configuration location besides artipie configs. In the case, when some external file with not proper format is met, we log the complaint about the file and start normally. Check #1242 for more details.

**Comment by CodeRemovalTechnician** [comment]
@olenagerasimova 

Thank you for stating your position on this matter and the changes you made.
To be honest, I don't really mind an error being logged as long as it does not prevent Artipie from starting: my only concern was that Artipie had to read duplicate files which could have lead to additional issues.

As for the `..2023_02_07_15_54_11.3145060576` folder, I am not clear on why it is been created but this is not something I can control (well I did not search for a solution...).

**Comment by CodeRemovalTechnician** [comment]
Hi, 

Just a small update after testing the v0.28.1 Docker image:  I can indeed see an error being raised because of invalid configuration files but I can also see duplicated repository files being loaded:

```
 〉kubectl logs -n artipie artipie-7df54bc4bd-7jq8x                                                                                                                Wed Feb  8 20:51:49 2023
[main] INFO com.artipie.VertxMain - Used version of Artipie: v0.28.1
[main] INFO org.eclipse.jetty.util.log - Logging initialized @6235ms to org.eclipse.jetty.util.log.Slf4jLog
[main] INFO org.reflections.Reflections - Reflections took 2397 ms to scan 1 urls, producing 36 keys and 78 values
[main] INFO com.artipie.asto.factory.Storages - Initiated storage factory [type=fs, class=FileStorageFactory]
[main] INFO com.artipie.VertxMain - Artipie was started on port 8080
[Thread-10] INFO com.artipie.asto.fs.FileStorage - Found 24 objects by the prefix "" in /var/artipie/configs by /var/artipie/configs: [..2023_02_08_19_41_33.2696904242/_credentials.yaml, ..2023_02_08_19_41_33.2696904242/_storages.yaml, _credentials.yaml, _storages.yaml, repos/private/..2023_02_08_19_41_33.2158733928/binaries.yaml, repos/private/..2023_02_08_19_41_33.2158733928/docker-remote.yaml, repos/private/..2023_02_08_19_41_33.2158733928/docker.yaml, repos/private/..2023_02_08_19_41_33.2158733928/helm.yaml, repos/private/..2023_02_08_19_41_33.2158733928/maven-remote.yaml, repos/private/..2023_02_08_19_41_33.2158733928/maven.yaml, repos/private/..2023_02_08_19_41_33.2158733928/npm-remote.yaml, repos/private/..2023_02_08_19_41_33.2158733928/npm.yaml, repos/private/..2023_02_08_19_41_33.2158733928/pypi-remote.yaml, repos/private/..2023_02_08_19_41_33.2158733928/pypi.yaml, repos/private/binaries.yaml, repos/private/docker-remote.yaml, repos/private/docker.yaml, repos/private/helm.yaml, repos/private/maven-remote.yaml, repos/private/maven.yaml, repos/private/npm-remote.yaml, repos/private/npm.yaml, repos/private/pypi-remote.yaml, repos/private/pypi.yaml]
[main] ERROR com.artipie.VertxMain - Invalid repo config file ..2023_02_08_19_41_33.2696904242/_credentials: java.lang.IllegalStateException: Invalid repo configuration
        at com.artipie.settings.repo.RepoConfig.lambda$repoYaml$3(RepoConfig.java:240)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at com.artipie.settings.repo.RepoConfig.repoYaml(RepoConfig.java:239)
        at com.artipie.settings.repo.RepoConfig.port(RepoConfig.java:120)
        at com.artipie.VertxMain.startRepos(VertxMain.java:221)
        at com.artipie.VertxMain.start(VertxMain.java:129)
        at com.artipie.VertxMain.main(VertxMain.java:190)

[main] ERROR com.artipie.VertxMain - Invalid repo config file ..2023_02_08_19_41_33.2696904242/_storages: java.lang.IllegalStateException: Invalid repo configuration
        at com.artipie.settings.repo.RepoConfig.lambda$repoYaml$3(RepoConfig.java:240)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at com.artipie.settings.repo.RepoConfig.repoYaml(RepoConfig.java:239)
        at com.artipie.settings.repo.RepoConfig.port(RepoConfig.java:120)
        at com.artipie.VertxMain.startRepos(VertxMain.java:221)
        at com.artipie.VertxMain.start(VertxMain.java:129)
        at com.artipie.VertxMain.main(VertxMain.java:190)

[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/..2023_02_08_19_41_33.2158733928/binaries' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/..2023_02_08_19_41_33.2158733928/docker-remote' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/..2023_02_08_19_41_33.2158733928/docker' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/..2023_02_08_19_41_33.2158733928/helm' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/..2023_02_08_19_41_33.2158733928/maven-remote' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/..2023_02_08_19_41_33.2158733928/maven' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/..2023_02_08_19_41_33.2158733928/npm-remote' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/..2023_02_08_19_41_33.2158733928/npm' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/..2023_02_08_19_41_33.2158733928/pypi-remote' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/..2023_02_08_19_41_33.2158733928/pypi' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/binaries' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/docker-remote' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/docker' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/helm' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/maven-remote' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/maven' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/npm-remote' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/npm' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/pypi-remote' was started on port 8080
[main] INFO com.artipie.VertxMain - Artipie repo 'repos/private/pypi' was started on port 8080
[vertx-blocked-thread-checker] WARN io.vertx.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2602 ms, time limit is 2000 ms
[vertx-blocked-thread-checker] WARN io.vertx.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 3602 ms, time limit is 2000 ms
[vertx-blocked-thread-checker] WARN io.vertx.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 4605 ms, time limit is 2000 ms
[vertx-blocked-thread-checker] WARN io.vertx.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 5604 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
        at app//io.vertx.ext.web.openapi.RouterBuilder.create(RouterBuilder.java:238)
        at app//io.vertx.ext.web.openapi.RouterBuilder.create(RouterBuilder.java:211)
        at app//com.artipie.api.RestApi.start(RestApi.java:131)
        at app//io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
        at app//io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
        at app//io.vertx.core.impl.DeploymentManager$$Lambda$361/0x0000000800e60af8.handle(Unknown Source)
        at app//io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at app//io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
        at app//io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
        at app//io.vertx.core.impl.EventLoopContext$$Lambda$362/0x0000000800e60d20.run(Unknown Source)
        at app//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
[vertx-blocked-thread-checker] WARN io.vertx.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2398 ms, time limit is 2000 ms
[vertx-blocked-thread-checker] WARN io.vertx.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 3398 ms, time limit is 2000 ms
[vert.x-eventloop-thread-1] INFO com.artipie.api.RestApi - Rest API started on port 8086, swagger is available on http://localhost:8086/api/index-org.html
```

It does not seem to be blocking the startup process anyway.
