### ISSUE TITLE
npm publish not working for npm version above 8

### ISSUE THREAD

**Issue by Zeratyl06** [artipie/artipie#1276]
Hi Team,

Problem when working with npm repository. Publishing a package using npm 6.14.18 is successful. The same package publishing with npm version 8.5.0 fails. The registry is registered in the .npmrc file.

.npmrc
```
//artipie.b2b-center.ru/:_authToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
```

commands
```
npm publish @hello/simple-npm-project --registry http://artipie.b2b-center.ru/npm
npm unpublish @hello/simple-npm-project -f --registry http://artipie.b2b-center.ru/npm
```

npm 6.14.18
```
connection: keep-alive
user-agent: npm/6.14.18 node/v14.21.3 linux x64
npm-in-ci: false
npm-scope:
npm-session: 1f981448fdb95f14
referer: publish [REDACTED]
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
content-type: application/json
accept: */*
accept-encoding: gzip,deflate
Host: artipie.b2b-center.ru
content-length: 1301
Apr 11, 2023 2:16:47 PM com.artipie.asto.LoggingStorage log
INFO: Save 'npm/@hello/simple-npm-project-a2fe4cde-ba9c-488d-b23b-88922fabe554-uploaded': Optional[1301]
Apr 11, 2023 2:16:47 PM com.artipie.asto.LoggingStorage log
INFO: Value 'npm/@hello/simple-npm-project-a2fe4cde-ba9c-488d-b23b-88922fabe554-uploaded': Optional[1301]
Apr 11, 2023 2:16:47 PM com.artipie.asto.LoggingStorage log
INFO: Exists 'npm/@hello/simple-npm-project/meta.json': false
Apr 11, 2023 2:16:47 PM com.artipie.asto.LoggingStorage log
INFO: Save 'npm/@hello/simple-npm-project/-/@hello/simple-npm-project-1.0.1.tgz': Optional[307]
Apr 11, 2023 2:16:47 PM com.artipie.asto.LoggingStorage log
INFO: Save 'npm/@hello/simple-npm-project/meta.json': Optional.empty
Apr 11, 2023 2:16:47 PM com.artipie.asto.LoggingStorage log
INFO: Delete 'npm/@hello/simple-npm-project-a2fe4cde-ba9c-488d-b23b-88922fabe554-uploaded'
[Thread-50] INFO com.artipie.http.MainSlice - << OK
[vert.x-eventloop-thread-0] INFO com.artipie.http.MainSlice - >> GET /npm/@hello%2fsimple-npm-project?write=true HTTP_1_1

connection: keep-alive
user-agent: npm/6.14.18 node/v14.21.3 linux x64
npm-in-ci: false
npm-scope:
npm-session: 6a0496bb62f803c4
referer: unpublish [REDACTED]
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
accept: */*
accept-encoding: gzip,deflate
Host: artipie.b2b-center.ru
Apr 11, 2023 2:16:56 PM com.artipie.asto.LoggingStorage log
INFO: Exists 'npm/@hello/simple-npm-project/meta.json': true
Apr 11, 2023 2:16:56 PM com.artipie.asto.LoggingStorage log
INFO: Value 'npm/@hello/simple-npm-project/meta.json': Optional[867]
[Thread-54] INFO com.artipie.http.MainSlice - << OK
Content-Type: application/json
[vert.x-eventloop-thread-0] INFO com.artipie.http.MainSlice - >> DELETE /npm/@hello%2fsimple-npm-project/-rev/undefined HTTP_1_1

connection: keep-alive
user-agent: npm/6.14.18 node/v14.21.3 linux x64
npm-in-ci: false
npm-scope:
npm-session: 6a0496bb62f803c4
referer: unpublish [REDACTED]
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
accept: */*
accept-encoding: gzip,deflate
Host: artipie.b2b-center.ru
[Thread-57] INFO com.artipie.asto.fs.FileStorage - Found 2 objects by the prefix "npm/@hello/simple-npm-project" in default by default/npm/@hello/simple-npm-project: [npm/@hello/simple-npm-project/-/@hello/simple-npm-project-1.0.1.tgz, npm/@hello/simple-npm-project/meta.json]
Apr 11, 2023 2:16:56 PM com.artipie.asto.LoggingStorage log
INFO: List 'npm/@hello/simple-npm-project': 2
Apr 11, 2023 2:16:56 PM com.artipie.asto.LoggingStorage log
INFO: Delete 'npm/@hello/simple-npm-project/-/@hello/simple-npm-project-1.0.1.tgz'
Apr 11, 2023 2:16:56 PM com.artipie.asto.LoggingStorage log
INFO: Delete 'npm/@hello/simple-npm-project/meta.json'
[Thread-59] INFO com.artipie.http.MainSlice - << OK
```

npm 8.5.0
```
user-agent: npm/8.5.0 node/v16.14.2 linux x64 workspaces/false
pacote-version: 12.0.3
pacote-req-type: packument
pacote-pkg-id: registry:@hello/simple-npm-project
accept: application/json
npm-command: publish
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
Accept-Encoding: gzip,deflate
Host: artipie.b2b-center.ru
Connection: keep-alive
[vert.x-eventloop-thread-0] INFO com.artipie.http.MainSlice - >> GET /npm/npm HTTP_1_1

user-agent: npm/8.5.0 node/v16.14.2 linux x64 workspaces/false
pacote-version: 12.0.3
pacote-req-type: packument
pacote-pkg-id: registry:npm
accept: application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*
npm-command: publish
authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...
Accept-Encoding: gzip,deflate
Host: artipie.b2b-center.ru
Connection: keep-alive
[Thread-63] INFO com.artipie.http.MainSlice - << OK
Apr 11, 2023 2:21:35 PM com.artipie.asto.LoggingStorage log
INFO: Exists 'npm/@hello/simple-npm-project/meta.json': false
[Thread-70] INFO com.artipie.http.MainSlice - << NOT_FOUND
```

error
```
npm ERR! code E404
npm ERR! 404 Not Found - GET http://artipie.b2b-center.ru/npm/@hello%2fsimple-npm-project
npm ERR! 404
npm ERR! 404  '@hello/simple-npm-project@latest' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-11T14_21_35_057Z-debug-0.log
```

**Comment by olenagerasimova** [comment]
@Zeratyl06 hi, thanks for reporting. I did not understand when exactly the problem appears: when you are trying to publish the package or when you are trying to UNpublish it?

**Comment by Zeratyl06** [comment]
When I publish a package that has never been in the registry before. Once a package is initially published with version 6.14.18, new versions of the package can be published and unpublished using version 8.5.0. Initially publishing a package with version 8.5.0 fails, with the above error.

**Comment by Zeratyl06** [comment]
The problem persists on version 9.

```
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@9.5.0
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 4ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/root/.npmrc Completed in 2ms
11 timing config:load:user Completed in 2ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:setEnvs Completed in 1ms
15 timing config:load Completed in 13ms
16 timing npm:load:configload Completed in 13ms
17 timing npm:load:mkdirpcache Completed in 1ms
18 timing npm:load:mkdirplogs Completed in 0ms
19 verbose title npm publish @hello/simple-npm-project
20 verbose argv "publish" "@hello/simple-npm-project" "--registry" "http://artipie.b2b-center.ru/npm"
21 timing npm:load:setTitle Completed in 2ms
22 timing config:load:flatten Completed in 3ms
23 timing npm:load:display Completed in 4ms
24 verbose logfile logs-max:10 dir:/root/.npm/_logs/2023-04-12T07_41_48_949Z-
25 verbose logfile /root/.npm/_logs/2023-04-12T07_41_48_949Z-debug-0.log
26 timing npm:load:logFile Completed in 7ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 29ms
30 verbose publish [ '@hello/simple-npm-project' ]
31 silly logfile done cleaning log files
32 http fetch GET 200 http://artipie.b2b-center.ru/npm/npm 73ms (cache miss)
33 http fetch GET 404 http://artipie.b2b-center.ru/npm/@hello%2fsimple-npm-project 85ms (cache skip)
34 http fetch GET 404 http://artipie.b2b-center.ru/npm/@hello%2fsimple-npm-project 24ms (cache skip)
35 timing command:publish Completed in 121ms
36 verbose stack HttpErrorGeneral: 404 Not Found - GET http://artipie.b2b-center.ru/npm/@hello%2fsimple-npm-project
36 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
36 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
36 verbose stack     at async RegistryFetcher.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:87:19)
36 verbose stack     at async RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:23)
36 verbose stack     at async Publish.getManifest (/usr/local/lib/node_modules/npm/lib/commands/publish.js:209:18)
36 verbose stack     at async Publish.exec (/usr/local/lib/node_modules/npm/lib/commands/publish.js:72:20)
36 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:134:5)
37 verbose statusCode 404
38 verbose pkgid @hello/simple-npm-project@*
39 verbose cwd /root
40 verbose Linux 5.15.90.1-microsoft-standard-WSL2
41 verbose node v18.15.0
42 verbose npm  v9.5.0
43 error code E404
44 error 404 Not Found - GET http://artipie.b2b-center.ru/npm/@hello%2fsimple-npm-project
45 error 404
46 error 404  '@hello/simple-npm-project@*' is not in this registry.
47 error 404
47 error 404 Note that you can also install from a
48 error 404 tarball, folder, http url, or git url.
49 verbose exit 1
50 timing npm Completed in 175ms
51 verbose code 1
52 error A complete log of this run can be found in:
52 error     /root/.npm/_logs/2023-04-12T07_41_48_949Z-debug-0.log
```

**Comment by olenagerasimova** [comment]
@Zeratyl06 as a quick fix, add a slash at the end of the package name 
`@hello/simple-npm-project/` instead of `@hello/simple-npm-project`

I'll fix this and let you know when done

**Comment by Zeratyl06** [comment]
Works! Thank you :)

**Comment by 1oglop1** [comment]
@olenagerasimova What do you mean by adding a slash to the package name? 

`package.json`
```json
{
  "name": "@hello/npm-project",
  "version": "1.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```
Changing the value in `package.json` means creating an invalid package (`@hello/npm-project` -> `@hello/npm-project/`  )

`npm ERR! Invalid name: "npm-project/"`

**Comment by olenagerasimova** [comment]
@1oglop1 adding a slash at the end of the package name in the npm `publish` command: 
```
npm publish @hello/simple-npm-project/ --registry http://your-address.com/my-npm
```

**Comment by 1oglop1** [comment]
> @1oglop1 adding a slash at the end of the package name in the npm `publish` command:
> 
> ```
> npm publish @hello/simple-npm-project/ --registry http://your-address.com/my-npm
> ```



I see, unfortunately that won't works unless the directory name is `@hello/simple-npm-project` - which is nearly never. And this breaks all JS tools common `npm`, `pnpm`, `yarn`. 

Because publishing always looks at the `package.json` so I see this issue as a major problem. 

Please check the documentation on the resolution https://docs.npmjs.com/cli/v9/commands/npm-publish?v=true#description

**Comment by olenagerasimova** [comment]
Maybe someone here knows npm well and can tell me, why npm registry itself do not allow to publish package:
```
MacBook-Pro-Alena:~ alenagerasimova$ npm publish @hello/simple-npm-project --loglevel verbose
npm verb cli /usr/local/bin/node /usr/local/bin/npm
npm info using npm@9.2.0
npm info using node@v19.3.0
npm verb title npm publish @hello/simple-npm-project
npm verb argv "publish" "@hello/simple-npm-project" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/Users/alenagerasimova/.npm/_logs/2023-04-28T06_34_33_397Z-
npm verb logfile /Users/alenagerasimova/.npm/_logs/2023-04-28T06_34_33_397Z-debug-0.log
npm verb publish [ '@hello/simple-npm-project' ]
npm http fetch GET 404 https://registry.npmjs.org/@hello%2fsimple-npm-project 148ms (cache skip)
npm http fetch GET 404 https://registry.npmjs.org/@hello%2fsimple-npm-project 25ms (cache skip)
npm verb stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@hello%2fsimple-npm-project - Not found
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
npm verb stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm verb stack     at async RegistryFetcher.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:85:19)
npm verb stack     at async RegistryFetcher.manifest (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:116:23)
npm verb stack     at async Publish.getManifest (/usr/local/lib/node_modules/npm/lib/commands/publish.js:207:18)
npm verb stack     at async Publish.exec (/usr/local/lib/node_modules/npm/lib/commands/publish.js:70:20)
npm verb stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:133:5)
npm verb statusCode 404
npm verb pkgid @hello/simple-npm-project@*
npm verb cwd /Users/alenagerasimova
npm verb Darwin 22.1.0
npm verb node v19.3.0
npm verb npm  v9.2.0
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@hello%2fsimple-npm-project - Not found
npm ERR! 404 
npm ERR! 404  '@hello/simple-npm-project@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit 1
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alenagerasimova/.npm/_logs/2023-04-28T06_34_33_397Z-debug-0.log

```

**Comment by olenagerasimova** [comment]
and if I add slash at the end of package name, then it tries to publish the package
```
MacBook-Pro-Alena:~ alenagerasimova$ npm publish @hello/simple-npm-project/ --loglevel verbose
npm verb cli /usr/local/bin/node /usr/local/bin/npm
npm info using npm@9.2.0
npm info using node@v19.3.0
npm verb title npm publish @hello/simple-npm-project/
npm verb argv "publish" "@hello/simple-npm-project/" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/Users/alenagerasimova/.npm/_logs/2023-04-28T06_39_30_006Z-
npm verb logfile /Users/alenagerasimova/.npm/_logs/2023-04-28T06_39_30_006Z-debug-0.log
npm verb publish [ '@hello/simple-npm-project/' ]
npm notice 
npm notice 📦  @hello/simple-npm-project@1.0.1
npm notice === Tarball Contents === 
npm notice 28B  index.js    
npm notice 221B package.json
npm notice === Tarball Details === 
npm notice name:          @hello/simple-npm-project               
npm notice version:       1.0.1                                   
npm notice filename:      hello-simple-npm-project-1.0.1.tgz      
npm notice package size:  298 B                                   
npm notice unpacked size: 249 B                                   
npm notice shasum:        7063831d57666fa37e130179a6e77fd4dcc1897f
npm notice integrity:     sha512-HldGUpCJ5D7fh[...]XUsb1BPj2Z/6A==
npm notice total files:   2                                       
npm notice 
npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access
npm http fetch PUT 402 https://registry.npmjs.org/@hello%2fsimple-npm-project 899ms
npm verb stack HttpErrorGeneral: 402 Payment Required - PUT https://registry.npmjs.org/@hello%2fsimple-npm-project - You must sign up for private packages
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
npm verb stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm verb stack     at async publish (/usr/local/lib/node_modules/npm/node_modules/libnpmpublish/lib/publish.js:42:12)
npm verb stack     at async otplease (/usr/local/lib/node_modules/npm/lib/utils/otplease.js:4:12)
npm verb stack     at async Publish.exec (/usr/local/lib/node_modules/npm/lib/commands/publish.js:126:7)
npm verb stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:133:5)
npm verb statusCode 402
npm verb pkgid @hello/simple-npm-project@1.0.1
npm verb cwd /Users/alenagerasimova
npm verb Darwin 22.1.0
npm verb node v19.3.0
npm verb npm  v9.2.0
npm ERR! code E402
npm ERR! 402 Payment Required - PUT https://registry.npmjs.org/@hello%2fsimple-npm-project - You must sign up for private packages
npm verb exit 1
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alenagerasimova/.npm/_logs/2023-04-28T06_39_30_006Z-debug-0.log
MacBook-Pro-Alena:~ alenagerasimova$
```

**Comment by 1oglop1** [comment]
@olenagerasimova 
I had some time to play around and published NPM package https://www.npmjs.com/package/@1oglop1/npm-package

By default, you can publish scoped packages only under your username so `@1oglop1/<package-name>`. see https://docs.npmjs.com/creating-and-publishing-scoped-public-packages
Here's what I did
1. I created an account
2. Created a Private Access Token 
3. configured `.npmrc` file with the content
    ```
    //registry.npmjs.org/:_authToken=${NPM_PAT_TOKEN}
    ```

4. Published the package `NPM_PAT_TOKEN=<my PAT> npm publish .`

During this exercise, I received several 404s as well.. I noticed that I had a typo in `.npmrc` file caused by Artipie docs 
https://github.com/artipie/artipie/wiki/npm due to the extensive use of curly braces `{ }` which are usually used by templating engines. 

![image](https://user-images.githubusercontent.com/7480694/235627001-cdf083bc-dc8f-4b6b-8ff4-2d8f2263bc6e.png)

In this case, I copied the string above and replaced `token` with `NPM_PAT_TOKEN` however I've been missing `$` to make it an [env var replacement](https://docs.npmjs.com/cli/v9/configuring-npm/npmrc#files). 
To fix the docs I'd suggest dropping `{ }` as placeholder indicator or rewrite to concrete examples. EG:
```
export NPM_TOKEN=$(curl -X POST -d '{"name": "admin", "pass": "admin"}' -H 'Content-type: application/json' "http://localhost:8086/api/v1/oauth/token" | jq -j .token)
```

PS. I was still not able to publish an NPM package to Artipie.

**Comment by olenagerasimova** [comment]
@1oglop1 what was the exact command you used to publish the package to npm registry?

**Comment by 1oglop1** [comment]
@olenagerasimova the one I mentioned in step4

> 4\. NPM_PAT_TOKEN=<my PAT> npm publish .


You can test the steps in my repository and also verify if my `artipie` configuration is correct 
https://github.com/1oglop1/artipie-test/tree/main
