### ISSUE TITLE
CI Test failed two times: AddWriterAstoTest.addChartsTrustfully

### ISSUE THREAD

**Issue by ChGen** [artipie/artipie#1358]
Test failed in GitHub CI two times with the same log.
`AddWriterAstoTest.addChartsTrustfully`

Log fragment:
```
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.artipie.helm.RemoveWriterAstoTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.343 s -- in com.artipie.helm.RemoveWriterAstoTest
[INFO] Running com.artipie.helm.HelmAstoReindexTest
Warning:  Tests run: 2, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.003 s -- in com.artipie.helm.HelmAstoReindexTest
[INFO] Running com.artipie.helm.TgzArchiveTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 s -- in com.artipie.helm.TgzArchiveTest
[INFO] Running com.artipie.helm.AddWriterAstoTest
Error:  Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.072 s <<< FAILURE! -- in com.artipie.helm.AddWriterAstoTest
Error:  com.artipie.helm.AddWriterAstoTest.addChartsTrustfully -- Time elapsed: 0.023 s <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.util.Map.computeIfAbsent(Object, java.util.function.Function)" because "this.mapping" is null
	at com.artipie.helm.metadata.IndexYamlMapping.entries(IndexYamlMapping.java:69)
	at com.artipie.helm.AddWriterAstoTest.addChartsTrustfully(AddWriterAstoTest.java:146)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

[INFO] Running com.artipie.helm.misc.SpaceInBeginningTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.027 s -- in com.artipie.helm.misc.SpaceInBeginningTest
......
[INFO] 
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:    AddWriterAstoTest.addChartsTrustfully:146 » NullPointer Cannot invoke "java.util.Map.computeIfAbsent(Object, java.util.function.Function)" because "this.mapping" is null
[INFO] 
Error:  Tests run: 75, Failures: 0, Errors: 1, Skipped: 3
```

**Comment by ChGen** [comment]
Fixed by https://github.com/artipie/artipie/pull/1377
