### ISSUE TITLE
Errors/corruption on uploading a 2nd rpm to a repo via curl

### ISSUE THREAD

**Issue by CJLove** [artipie/artipie#1363]
I'm running the `artipie/artipie:v0.30.12` image under Docker on a Fedora 38 host.

I have an rpm repo configured as follows:
```yaml
repo:
  type: rpm
  storage:
    type: fs
    path: /var/artipie/data/fedora38
  settings:
    digest: sha256
    naming-policy: sha1
    filelists: true
    update:
      on: upload
      on:
        cron: 5 14 * * *
```

The first upload via curl appears to succeed and `repodata` appears to be built successfully in the repo's data directory. I can list the rpms in the repo using `yum` and see the rpm listed.

The second rpm upload via curl results in the following output both from the terminal where curl was run as well as in the artipie container logs:
```
[INFO] 2024-01-08 00:58:39,913 ForkJoinPool.commonPool-worker-13 com.artipie.http.MainSlice - Failure: java.util.concurrent.CompletionException: com.artipie.asto.ArtipieIOException: java.nio.file.NoSuchFileException: /var/artipie/data/fedora38/fedora38/repodata
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: com.artipie.asto.ArtipieIOException: java.nio.file.NoSuchFileException: /var/artipie/data/fedora38/fedora38/repodata
	at com.artipie.asto.fs.FileStorage.deleteEmptyParts(FileStorage.java:269)
	at com.artipie.asto.fs.FileStorage.lambda$delete$12(FileStorage.java:179)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	... 6 more
Caused by: java.nio.file.NoSuchFileException: /var/artipie/data/fedora38/fedora38/repodata
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.asIOException(UnixException.java:115)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:477)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:481)
	at java.base/java.nio.file.Files.list(Files.java:3772)
	at com.artipie.asto.fs.FileStorage.deleteEmptyParts(FileStorage.java:259)
	... 8 more
```
At this point in the repo's data directory:
- The `repodata` directory is gone
- The 2nd rpm file is present in the `.add` directory
- An `.artipie-locks` directory exists
- Another directory exists (looks like a UUID for the directory name) with what looks like rpm repo data files present.

**Comment by olenagerasimova** [comment]
@CJLove hi, first of all, your repository settings yaml file is not valid: yaml mapping cannot have two values with the same name. You should either set update on upload
```yaml
repo:
  type: rpm
  storage:
    type: fs
    path: /var/artipie/data/fedora38
  settings:
    digest: sha256
    naming-policy: sha1
    filelists: true
    update:
      on: upload
```
or by cron schedule:
```yaml
repo:
  type: rpm
  storage:
    type: fs
    path: /var/artipie/data/fedora38
  settings:
    digest: sha256
    naming-policy: sha1
    filelists: true
    update:
      on:
        cron: 0 2 * * *
```

I'll check the case with second file upload separately and let you know if some problems were found.

**Comment by CJLove** [comment]
Thanks! With the configuration fix I've been able to upload multiple rpms via curl. Closing this now.
