### ISSUE TITLE
Docker hub proxy fails with logging errors

### ISSUE THREAD

**Issue by vyakovlev-hw** [artipie/artipie#1394]
I use the latest `docker image` as of Feb 1st with proxy settings for `dockerhub` when `artipie` is behind a corporate proxy

My config is:
```
repo:
  type: docker-proxy
  # optional, storage to cache pulled images and to enable push operation
  storage:
    type: fs
    path: /var/artipie/repo/data/dockerhub
  # optional; if not defined, then will be used settings form `meta` config
  http_client:
    # all fields are optional
    connection_timeout: 25000
    idle_timeout: 500
    trust_all: true
    follow_redirects: true
#    http3: true
#    jks:
#      path: /var/artipie/keystore.jks
#      password: secret
    proxies:
      - url: http://172.17.0.1:3128
  remotes:
    - url: registry-1.docker.io
```

`http://172.17.0.1:3128` is a cntlm proxy, I see the following requests from my docker container:
```
Feb 01 13:10:16 vy-vm.mydomain.com cntlm[2047]: cntlm[2047]: 172.17.0.3 CONNECT registry-1.docker.io:443
Feb 01 13:10:16 vy-vm.mydomain.com cntlm[2047]: 172.17.0.3 CONNECT registry-1.docker.io:443
Feb 01 13:10:17 vy-vm.mydomain.com cntlm[2047]: cntlm[2047]: 172.17.0.3 CONNECT auth.docker.io:443
Feb 01 13:10:17 vy-vm.mydomain.com cntlm[2047]: 172.17.0.3 CONNECT auth.docker.io:443
```

And the proxy can easily proxy these requests, e.g.
```
curl -v https://registry-1.docker.io:443
* Uses proxy env variable no_proxy == ...'
* Uses proxy env variable https_proxy == 'http://172.17.0.1:3128'
*   Trying 172.17.0.1:3128...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 172.17.0.1 (172.17.0.1) port 3128 (#0)
...
* Establish HTTP proxy tunnel to registry-1.docker.io:443
> CONNECT registry-1.docker.io:443 HTTP/1.1
> Host: registry-1.docker.io:443
> User-Agent: curl/7.72.0
> Proxy-Connection: Keep-Alive
...
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< content-type: text/plain; charset=utf-8
< docker-distribution-api-version: registry/2.0
```

When I try to pull an image from `artipie` (e.g. `docker pull vy-vm.mydomain.com:8080/dockerhub/artipie/artipie`, that should get it from `dockerhub` and serve me, I get the following message in `artipie` logs:
<p><details><summary>Click this to collapse/fold.</summary>
<pre><code>
[INFO] 2024-02-01 10:10:15,423 vert.x-eventloop-thread-0 com.artipie.http.MainSlice - >> GET /v2/ HTTP_1_1

Host: vy-vm.mydomain.com:8080
User-Agent: docker/20.10.23 go/go1.18.10 git-commit/6051f14 kernel/5.4.0-128-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.23 \(linux\))
Accept-Encoding: gzip
Connection: close
[INFO] 2024-02-01 10:10:15,441 vert.x-eventloop-thread-0 com.artipie.http.MainSlice - << UNAUTHORIZED
WWW-Authenticate: Basic realm="artipie"
[INFO] 2024-02-01 10:10:15,468 vert.x-eventloop-thread-0 com.artipie.http.MainSlice - >> HEAD /v2/dockerhub/artipie/artipie/manifests/latest HTTP_1_1

Host: vy-vm.mydomain.com:8080
User-Agent: docker/20.10.23 go/go1.18.10 git-commit/6051f14 kernel/5.4.0-128-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.23 \(linux\))
Accept: application/vnd.docker.distribution.manifest.v2+json
Accept: application/vnd.docker.distribution.manifest.list.v2+json
Accept: application/vnd.oci.image.index.v1+json
Accept: application/vnd.docker.distribution.manifest.v1+prettyjws
Accept: application/json
Accept: application/vnd.oci.image.manifest.v1+json
Authorization: Basic somebase64==
Connection: close
[WARN] 2024-02-01 10:10:15,988 vert.x-eventloop-thread-0 org.eclipse.jetty.util.ssl.SslContextFactory.config - Trusting all certificates configured for Client@1c51ac88[provider=null,keyStore=null,trustStore=null
]
[WARN] 2024-02-01 10:10:15,988 vert.x-eventloop-thread-0 org.eclipse.jetty.util.ssl.SslContextFactory.config - No Client EndPointIdentificationAlgorithm configured for Client@1c51ac88[provider=null,keyStore=null
,trustStore=null]
[INFO] 2024-02-01 10:10:16,069 vert.x-eventloop-thread-0 com.artipie.settings.cache.CachedUsers - Successfully authenticated 'docker' user via CachedUsers(size=1),origin=Joined([Joined([AuthFromEnv(),GithubAuth(
)]),AuthFromStorage])
Feb 01, 2024 10:10:16 AM com.artipie.asto.LoggingStorage log
INFO: Exists 'dockerhub/docker/registry/v2/repositories/artipie/artipie/_manifests/tags/latest/current/link': false
[ERROR] 2024-02-01 10:10:19,384 HttpClient@7ed9d04c-117 com.artipie.docker.cache.CacheManifests - Failed to cache manifest latest: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot
 invoke "javax.json.JsonObject.getString(String)" because the return value of "javax.json.JsonObject.getJsonObject(String)" is null
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
        at com.artipie.http.client.jetty.JettyClientSlice.lambda$response$3(JettyClientSlice.java:108)
        at org.eclipse.jetty.client.transport.ResponseListeners.notifyComplete(ResponseListeners.java:349)
        at org.eclipse.jetty.client.transport.ResponseListeners.notifyComplete(ResponseListeners.java:341)
        at org.eclipse.jetty.client.transport.HttpReceiver.terminateResponse(HttpReceiver.java:417)
        at org.eclipse.jetty.client.transport.HttpReceiver.terminateResponse(HttpReceiver.java:399)
        at org.eclipse.jetty.client.transport.HttpReceiver.lambda$responseSuccess$3(HttpReceiver.java:364)
        at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
        at org.eclipse.jetty.client.transport.HttpReceiver.lambda$responseSuccess$3(HttpReceiver.java:364)                                                                                              [1519/4084]
        at org.eclipse.jetty.util.thread.SerializedInvoker$Link.run(SerializedInvoker.java:191)
        at org.eclipse.jetty.util.thread.SerializedInvoker.run(SerializedInvoker.java:117)
        at org.eclipse.jetty.client.transport.HttpReceiver.responseHeaders(HttpReceiver.java:240)
        at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.lambda$headerComplete$2(HttpReceiverOverHTTP.java:435)
        at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:320)
        at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.parseAndFill(HttpReceiverOverHTTP.java:250)
        at org.eclipse.jetty.client.transport.internal.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:76)
        at org.eclipse.jetty.client.transport.internal.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:90)
        at org.eclipse.jetty.client.transport.internal.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:194)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.ssl.SslConnection$SslEndPoint.onFillable(SslConnection.java:555)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:374)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:147)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1196)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1151)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "javax.json.JsonObject.getString(String)" because the return value of "javax.json.JsonObject.getJsonObject(String)" is null
        at com.artipie.docker.manifest.JsonManifest.config(JsonManifest.java:88)
        at com.artipie.docker.cache.CacheManifests.lambda$copy$8(CacheManifests.java:122)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        ... 33 more

[INFO] 2024-02-01 10:10:19,394 HttpClient@7ed9d04c-117 com.artipie.http.MainSlice - << BAD_REQUEST
Content-Length: 117
Content-Type: application/json; charset=utf-8
[INFO] 2024-02-01 10:10:19,399 vert.x-eventloop-thread-0 com.artipie.http.MainSlice - >> GET /v2/dockerhub/artipie/artipie/manifests/latest HTTP_1_1

Host: vy-vm.mydomain.com:8080
User-Agent: docker/20.10.23 go/go1.18.10 git-commit/6051f14 kernel/5.4.0-128-generic os/linux arch/amd64 UpstreamClient(Docker-Client/20.10.23 \(linux\))
Accept: application/vnd.docker.distribution.manifest.v2+json
Accept: application/vnd.docker.distribution.manifest.list.v2+json
Accept: application/vnd.oci.image.index.v1+json
Accept: application/vnd.docker.distribution.manifest.v1+prettyjws
Accept: application/json
Accept: application/vnd.oci.image.manifest.v1+json
Authorization: Basic somebase64==
Accept-Encoding: gzip
Connection: close
[INFO] 2024-02-01 10:10:19,406 vert.x-eventloop-thread-0 com.artipie.settings.cache.CachedUsers - Successfully authenticated 'docker' user via CachedUsers(size=1),origin=Joined([Joined([AuthFromEnv(),GithubAuth(
)]),AuthFromStorage])
Feb 01, 2024 10:10:19 AM com.artipie.asto.LoggingStorage log
INFO: Exists 'dockerhub/docker/registry/v2/repositories/artipie/artipie/_manifests/tags/latest/current/link': false
[ERROR] 2024-02-01 10:10:21,627 HttpClient@7ed9d04c-110 com.artipie.docker.cache.CacheManifests - Failed to cache manifest latest: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot
 invoke "javax.json.JsonObject.getString(String)" because the return value of "javax.json.JsonObject.getJsonObject(String)" is null
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
...
</code></pre></details></p>

And the docker command fails with:
```
docker pull vy-vm.mydomain.com:8080/dockerhub/artipie/artipie
Using default tag: latest
Error response from daemon: manifest invalid: invalid manifest
```

Please advise.

**Comment by dgarus** [comment]
#1305 can be done here
