### ISSUE TITLE
The test RpmSliceS3ITCase is broken

### ISSUE THREAD

**Issue by dgarus** [artipie/artipie#1409]
The test failed with the following error

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fileStoreController' defined in class path resource [com/adobe/testing/s3mock/S3MockConfiguration.class]: Unsatisfied dependency expressed through method 'fileStoreController' parameter 0: Error creating bean with name 'objectService' defined in class path resource [com/adobe/testing/s3mock/service/ServiceConfiguration.class]: Unsatisfied dependency expressed through method 'objectService' parameter 1: Error creating bean with name 'objectStore' defined in class path resource [com/adobe/testing/s3mock/store/StoreConfiguration.class]: Failed to instantiate [com.adobe.testing.s3mock.store.ObjectStore]: Factory method 'objectStore' threw exception with message: jakarta/xml/bind/JAXBException

	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:542)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1164)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:149)
	at com.adobe.testing.s3mock.S3MockApplication.start(S3MockApplication.java:199)
```

**Comment by ChGen** [comment]
It was fixed in the PR above.
