### ISSUE TITLE
running artipie with Java 17 runtime

### ISSUE THREAD

**Issue by Tzahif** [artipie/artipie#1448]
I am using the jar with dependencies v0.30.14, and i need to run it on an environment with Java 17.
i am getting this error:
```
artipie                                | Error: LinkageError occurred while loading main class com.artipie.VertxMain
artipie                                | 	java.lang.UnsupportedClassVersionError: com/artipie/VertxMain has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```

is there an option to release artipie to support Java 17 runtime?

**Comment by mikra01** [comment]
@Tzahif I compiled it locally but faced some issues (regarding the jdk17-build branch build on windows. Compile it with "mvn package -P jar-build -DskipTests") but I attached you the patchfile. good luck.
---------------
diff --git a/artipie-core/pom.xml b/artipie-core/pom.xml
index 826bd944..d0d58131 100644
--- a/artipie-core/pom.xml
+++ b/artipie-core/pom.xml
@@ -66,6 +66,11 @@
       <artifactId>httpclient5</artifactId>
       <version>${httpclient.version}</version>
     </dependency>
+    <dependency>
+      <groupId>org.apache.httpcomponents.core5</groupId>
+      <artifactId>httpcore5-h2</artifactId>
+      <version>${httpcore5-h2.version}</version>
+    </dependency>
     <dependency>
       <groupId>org.quartz-scheduler</groupId>
       <artifactId>quartz</artifactId>
diff --git a/artipie-main/pom.xml b/artipie-main/pom.xml
index d5459dc7..3510807e 100644
--- a/artipie-main/pom.xml
+++ b/artipie-main/pom.xml
@@ -316,7 +316,7 @@ SOFTWARE.
                 <groupId>org.apache.maven.plugins</groupId>
                 <artifactId>maven-compiler-plugin</artifactId>
                 <configuration>
-                    <release>21</release>
+                    <release>17</release>
                 </configuration>
             </plugin>
         </plugins>
diff --git a/gem-adapter/pom.xml b/gem-adapter/pom.xml
index 5bc81efc..614acce5 100644
--- a/gem-adapter/pom.xml
+++ b/gem-adapter/pom.xml
@@ -164,7 +164,7 @@ SOFTWARE.
         <version>3.0.0</version>
         <groupId>org.codehaus.mojo</groupId>
         <executions>
-          <execution>
+          
         </executions>
       </plugin>
     </plugins>
diff --git a/http-client/pom.xml b/http-client/pom.xml
index 4c5487f1..47dd10fb 100644
--- a/http-client/pom.xml
+++ b/http-client/pom.xml
@@ -44,6 +44,11 @@ SOFTWARE.
       <artifactId>artipie-core</artifactId>
       <version>1.0-SNAPSHOT</version>
     </dependency>
+    <dependency>
+      <groupId>org.apache.httpcomponents.core5</groupId>
+      <artifactId>httpcore5-h2</artifactId>
+      <version>${httpcore5-h2.version}</version>
+    </dependency>
     <dependency>
       <groupId>org.eclipse.jetty</groupId>
       <artifactId>jetty-http</artifactId>
diff --git a/pom.xml b/pom.xml
index 93f5b3c5..e85db48e 100644
--- a/pom.xml
+++ b/pom.xml
@@ -85,6 +85,8 @@ SOFTWARE.
     <maven.compiler.release>17</maven.compiler.release>
     <header.license>LICENSE.header</header.license>
     <httpclient.version>5.3.1</httpclient.version>
+    <httpcore5-h2.version>5.2.4</httpcore5-h2.version>
+ 
   </properties>
   <distributionManagement>
     <repository>
---------------

**Comment by mikra01** [comment]
@Tzahif I compiled it locally but faced some issues (regarding the jdk17-build branch build on windows. Compile it with "mvn package -P jar-build -DskipTests") but I attached you the patchfile. good luck.
[jdk17_core5_patch.txt](https://github.com/artipie/artipie/files/15209354/jdk17_core5_patch.txt)

**Comment by Tzahif** [comment]
@ChGen @dgarus is there an option for official version based on Java 17?

**Comment by Tzahif** [comment]
@ChGen i have some constraints that i must use jdk17 based on another base image.

i was able to build `jdk17-builds` branch with @mikra01 patch, but when i am running it i am facing this error:
```
artipie-2                                    | 2024-05-27 19:49:21.800 INFO  MainSlice:241 [sdk-async-response-0-24] - Failure: java.util.concurrent.CompletionException: com.artipie.asto.ArtipieIOException: java.io.IOException: java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
artipie-2                                    | Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
artipie-2                                    | Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
test-machine-ubuntu-artipie                  | Ign:6 http://artifacts-repository-gateway-apt-artipie:8080/apt-test-repo apt-test-repo Release
artipie-2                                    | If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
artipie-2                                    | 	at com.artipie.asto.s3.S3Storage.lambda$exists$0(S3Storage.java:122)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
artipie-2                                    | 	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:76)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
artipie-2                                    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallMetricCollectionStage.lambda$execute$0(AsyncApiCallMetricCollectionStage.java:54)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
artipie-2                                    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$2(AsyncApiCallTimeoutTrackingStage.java:67)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
artipie-2                                    | 	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:76)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
artipie-2                                    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)
artipie-2                                    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:181)
artipie-2                                    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:159)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
artipie-2                                    | 	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:76)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
artipie-2                                    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:103)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
artipie-2                                    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:165)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
artipie-2                                    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
artipie-2                                    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
artipie-2                                    | 	at java.base/java.lang.Thread.run(Thread.java:840)
artipie-2                                    | Caused by: com.artipie.asto.ArtipieIOException: java.io.IOException: java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
artipie-2                                    | Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
artipie-2                                    | Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
artipie-2                                    | If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
artipie-2                                    | 	... 49 more
artipie-2                                    | Caused by: java.io.IOException: java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
artipie-2                                    | Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
artipie-2                                    | Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
artipie-2                                    | If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
artipie-2                                    | 	at com.artipie.asto.ArtipieIOException.unwrap(ArtipieIOException.java:73)
artipie-2                                    | 	at com.artipie.asto.ArtipieIOException.<init>(ArtipieIOException.java:41)
artipie-2                                    | 	... 49 more
artipie-2                                    | Caused by: java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
artipie-2                                    | Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
artipie-2                                    | Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
artipie-2                                    | If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
artipie-2                                    | 	at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:62)
artipie-2                                    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
artipie-2                                    | 	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
artipie-2                                    | 	... 31 more
artipie-2                                    | Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
artipie-2                                    | Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
artipie-2                                    | Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
artipie-2                                    | If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
artipie-2                                    | 	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:102)
artipie-2                                    | 	at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47)
artipie-2                                    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:204)
artipie-2                                    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:200)
artipie-2                                    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:179)
artipie-2                                    | 	... 22 more
artipie-2                                    | Caused by: java.lang.Throwable: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
artipie-2                                    | Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
artipie-2                                    | Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
artipie-2                                    | If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.
artipie-2                                    | 	at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.decorateException(NettyUtils.java:63)
artipie-2                                    | 	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.handleFailure(NettyRequestExecutor.java:310)
artipie-2                                    | 	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.makeRequestListener(NettyRequestExecutor.java:189)
artipie-2                                    | 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
artipie-2                                    | 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
artipie-2                                    | 	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
artipie-2                                    | 	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:503)
artipie-2                                    | 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
artipie-2                                    | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
artipie-2                                    | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
artipie-2                                    | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
artipie-2                                    | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
artipie-2                                    | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
artipie-2                                    | 	... 1 more
artipie-2                                    | Caused by: java.util.concurrent.TimeoutException: Acquire operation took longer than 10000 milliseconds.
artipie-2                                    | 	at software.amazon.awssdk.http.nio.netty.internal.HealthCheckedChannelPool.timeoutAcquire(HealthCheckedChannelPool.java:77)
artipie-2                                    | 	at software.amazon.awssdk.http.nio.netty.internal.HealthCheckedChannelPool.lambda$acquire$0(HealthCheckedChannelPool.java:67)
artipie-2                                    | 	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
artipie-2                                    | 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
artipie-2                                    | 	... 7 more
artipie-2                                    |
```

this error doesn't happen on the main branch.
@ChGen @mikra01 do you have any suggestions how to fix it?

**Comment by ChGen** [comment]
@Tzahif , I suspect it won't be the only problem. You can try here to update (or downgrade?) version of amazon awssdk... Do you have docker image size constraint? If not, you could install there jdk21 too and use it just for artipie process.
