### ISSUE TITLE
Unclear error on missed permissions config

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#182]
Steps to reproduce: 

```
mkdir -p artipie-test/repo && cd artipie-test
echo "repo:
  type: file
  storage:
    type: fs
    path: /var/artipie" > repo/fs.yaml
docker run -d -v  "$(pwd):/var/artipie" -p 8080:80 artipie/artipie:0.3.3
curl -X PUT -i --data-binary "123" http://localhost:8080/fs/123.txt
HTTP/1.1 500 Internal Server Error
content-length: 3005

java.util.concurrent.CompletionException: java.lang.NullPointerException
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:60)
	at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
	at wtf.g4s8.rio.file.ReadSubscriberState.onComplete(ReadSubscriberState.java:76)
	at wtf.g4s8.rio.file.ReadRequest$Next.process(ReadRequest.java:127)
	at wtf.g4s8.rio.file.ReadTaskQueue.run(ReadTaskQueue.java:93)
	at wtf.g4s8.rio.file.CloseChanOnError.run(CloseChanOnError.java:25)
	at wtf.g4s8.rio.file.ErrorOnException.run(ErrorOnException.java:33)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.artipie.RpPermissions.allowed(RpPermissions.java:69)
	at com.artipie.http.auth.Permission$ByName.allowed(Permission.java:67)
	at com.artipie.http.auth.SliceAuth.lambda$response$1(SliceAuth.java:96)
	at java.base/java.util.Optional.orElseGet(Unknown Source)
	at com.artipie.http.auth.SliceAuth.response(SliceAuth.java:93)
	at com.artipie.http.rt.SliceRoute$Path.response(SliceRoute.java:141)
	at com.artipie.http.rt.SliceRoute.lambda$response$0(SliceRoute.java:86)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at com.artipie.http.rt.SliceRoute.response(SliceRoute.java:89)
	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
	at com.artipie.http.async.AsyncSlice.lambda$response$0(AsyncSlice.java:63)
	... 15 more
```

Also, stack trace in the response is not descriptive and does not give any idea to a user what is wrong.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@Sammers21 it seems you didn't configure permission settings:
```
Caused by: java.lang.NullPointerException
	at com.artipie.RpPermissions.allowed(RpPermissions.java:69)
	at com.artipie.http.auth.Permission$ByName.allowed(Permission.java:67)
	at com.artipie.http.auth.SliceAuth.lambda$response$1(SliceAuth.java:96)
```
See: https://github.com/artipie/artipie#yaml-credentials-file

But you are right, we have to return some meaningful error message in that case.

**Comment by 0crat** [comment]
The job [#182](https://github.com/artipie/artipie/issues/182) assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/1eee5535-0266-4720-8ab1-9032a2cddf3d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Sammers21** [comment]
@g4s8, I'm just curious why permissions are required by default?

**Comment by Sammers21** [comment]
Just give the user what he expects: permissions not configured - permission is not required, permissions are configured - let him use it

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
