### ISSUE TITLE
hit ENTER without entering the password: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by yegor256** [artipie/artipie#214]
```
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.single.SingleZipArray$ZipCoordinator.innerSuccess(SingleZipArray.java:119)
	at io.reactivex.internal.operators.single.SingleZipArray$ZipSingleObserver.onSuccess(SingleZipArray.java:170)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
	at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
	at wtf.g4s8.rio.file.ReadSubscriberState.onComplete(ReadSubscriberState.java:76)
	at wtf.g4s8.rio.file.ReadRequest$Next.process(ReadRequest.java:127)
	at wtf.g4s8.rio.file.ReadTaskQueue.run(ReadTaskQueue.java:93)
	at wtf.g4s8.rio.file.CloseChanOnError.run(CloseChanOnError.java:25)
	at wtf.g4s8.rio.file.ErrorOnException.run(ErrorOnException.java:33)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.artipie.http.auth.BasicIdentities.lambda$user$3(BasicIdentities.java:66)
	at java.base/java.util.Optional.flatMap(Optional.java:287)
	at com.artipie.http.auth.BasicIdentities.user(BasicIdentities.java:66)
	at com.artipie.api.AuthApi.user(AuthApi.java:84)
	at com.artipie.http.auth.SliceAuth.response(SliceAuth.java:83)
	at com.artipie.http.async.AsyncSlice.lambda$response$0(AsyncSlice.java:63)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 19 more
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8), @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#214](https://github.com/artipie/artipie/issues/214) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/4dcc700e-1bc9-4176-8240-21c1f1df9d82); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by victornoel** [comment]
@yegor256 what is the command you ran to get this? where is this password prompt?

**Comment by victornoel** [comment]
@0crat wait for answer

**Comment by victornoel** [comment]
@yegor256 ping

**Comment by victornoel** [comment]
@yegor256 ?

**Comment by victornoel** [comment]
@yegor256 can you clarify this ticket please?

**Comment by g4s8** [comment]
@victornoel @yegor256 this issue seems to be obsolete, since we don't have reset password form which may produce this stacktrace.

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/artipie/artipie/issues/214#issuecomment-662293327))

@g4s8 The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#214](https://github.com/artipie/artipie/issues/214), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#214` is not assigned, can't get performer
