### ISSUE TITLE
Non user-friendly startup error

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#304]
If I would just run artipie without any options. A stack trace is printed: 

```bash
$ docker run artipie/artipie:0.8.9
Exception in thread "main" java.lang.NullPointerException
	at com.artipie.VertxMain.metrics(VertxMain.java:142)
	at com.artipie.VertxMain.main(VertxMain.java:125)
```

It is a very bad way to tell a user that he should provide options.

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#304` is not assigned, can't get performer
