### ISSUE TITLE
Java exception if : is missing in the yaml file 

### ISSUE THREAD

**Issue by jeffzhu503** [artipie/artipie#320]
I am updating YAML config of your repository in central.artipie as the following.  I did not add ":" after the account name
repo:
  type: file
  storage: default
  permissions:
    jeffzhu503
      - upload
      - download 
I hit the exception which shall be handled gracefully with the yaml file formatting error. 

java.util.concurrent.CompletionException: com.amihaiemil.eoyaml.exceptions.YamlIndentationException: Indentation of line 6 [- upload] is greater than the one of line 5 [jeffzhu503]. It should be less or equal.
java.util.concurrent.CompletionException: com.amihaiemil.eoyaml.exceptions.YamlIndentationException: Indentation of line 6 [- upload] is greater than the one of line 5 [jeffzhu503]. It should be less or equal.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:116)
	at io.reactivex.internal.operators.completable.CompletableToSingle$ToSingle.onError(CompletableToSingle.java:74)
	at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onError(SingleFlatMapCompletable.java:97)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onError(SingleFlatMap.java:116)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:60)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
	at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
	at wtf.g4s8.rio.file.ReadSubscriberState.onComplete(ReadSubscriberState.java:76)
	at wtf.g4s8.rio.file.ReadRequest$Next.process(ReadRequest.java:127)
	at wtf.g4s8.rio.file.ReadTaskQueue.run(ReadTaskQueue.java:93)
	at wtf.g4s8.rio.file.CloseChanOnError.run(CloseChanOnError.java:25)
	at wtf.g4s8.rio.file.ErrorOnException.run(ErrorOnException.java:33)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.amihaiemil.eoyaml.exceptions.YamlIndentationException: Indentation of line 6 [- upload] is greater than the one of line 5 [jeffzhu503]. It should be less or equal.
	at com.amihaiemil.eoyaml.WellIndented.iterator(WellIndented.java:150)
	at com.amihaiemil.eoyaml.SameIndentationLevel.iterator(SameIndentationLevel.java:74)
	at com.amihaiemil.eoyaml.ReadYamlMapping.valueOfStringKey(ReadYamlMapping.java:236)
	at com.amihaiemil.eoyaml.ReadYamlMapping.value(ReadYamlMapping.java:180)
	at com.amihaiemil.eoyaml.YamlMapping.yamlMapping(YamlMapping.java:89)
	at com.amihaiemil.eoyaml.YamlMapping.yamlMapping(YamlMapping.java:77)
	at com.artipie.api.ApiRepoUpdateSlice.lambda$response$3(ApiRepoUpdateSlice.java:117)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
	... 13 more

**Comment by g4s8** [comment]
Let's return a human-readable error in case if yaml is not valid
