### ISSUE TITLE
Npm repo is broken

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#350]
__`npm_repo.yaml`__:
```yaml
repo:
  path: "http://localhost:8080/npm_repo/"
  type: npm
  storage:
    type: fs
    path: /var/artipie/data
  permissions:
    "*":
      - "*"
```

```bash
$ docker run  -it -v $(pwd)/artipie.yaml:/etc/artipie.yml -v $(pwd):/var/artipie -p 8080:80 artipie/artipie:latest
[INFO] 2020-07-17 05:43:15,025 main com.artipie.VertxMain - Artipie was started on port 80
[INFO] 2020-07-17 05:43:17,548 vert.x-eventloop-thread-1 com.artipie.http.DockerRoutingSlice - >> PUT /npm_repo/sample-npm-project HTTP_1_1

connection: keep-alive
user-agent: npm/6.14.6 node/v14.4.0 darwin x64
npm-in-ci: false
npm-scope:
npm-session: 7afc86cfc84eda83
referer: publish
content-type: application/json
accept: */*
content-length: 1751
accept-encoding: gzip,deflate
Host: localhost:8080
[INFO] 2020-07-17 05:43:17,589 FileStorage-2 org.eclipse.jetty.util.log - Logging initialized @3085ms to org.eclipse.jetty.util.log.Slf4jLog
[INFO] 2020-07-17 05:43:17,608 FileStorage-2 com.artipie.SliceFromConfig - Created HTTP client, trustall=false
[INFO] 2020-07-17 05:43:17,792 FileStorage-2 com.artipie.http.DockerRoutingSlice - Failure: java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void com.artipie.http.rt.SliceRoute.<init>(com.artipie.http.rt.SliceRoute$Path[])'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$MinimalStage.thenApply(Unknown Source)
	at com.artipie.SliceFromConfig.<init>(SliceFromConfig.java:128)
	at com.artipie.http.ArtipieRepositories.lambda$resolve$1(ArtipieRepositories.java:96)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
	at io.reactivex.subjects.SingleSubject.subscribeActual(SingleSubject.java:173)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
	at io.reactivex.internal.operators.single.SingleZipArray$ZipCoordinator.innerSuccess(SingleZipArray.java:119)
	at io.reactivex.internal.operators.single.SingleZipArray$ZipSingleObserver.onSuccess(SingleZipArray.java:170)
	at io.reactivex.subjects.SingleSubject.onSuccess(SingleSubject.java:141)
	at hu.akarnokd.rxjava2.interop.SingleInterop.lambda$fromFuture$2(SingleInterop.java:82)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'void com.artipie.http.rt.SliceRoute.<init>(com.artipie.http.rt.SliceRoute$Path[])'
	at com.artipie.npm.http.NpmSlice.<init>(NpmSlice.java:107)
	at com.artipie.SliceFromConfig.build(SliceFromConfig.java:187)
	at com.artipie.SliceFromConfig.lambda$new$0(SliceFromConfig.java:129)
	... 23 more

[INFO] 2020-07-17 05:43:27,813 vert.x-eventloop-thread-1 com.artipie.http.DockerRoutingSlice - >> PUT /npm_repo/sample-npm-project HTTP_1_1

connection: keep-alive
user-agent: npm/6.14.6 node/v14.4.0 darwin x64
npm-in-ci: false
npm-scope:
npm-session: 7afc86cfc84eda83
referer: publish
content-type: application/json
accept: */*
content-length: 1751
accept-encoding: gzip,deflate
Host: localhost:8080
[INFO] 2020-07-17 05:43:27,827 FileStorage-2 com.artipie.http.DockerRoutingSlice - Failure: java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void com.artipie.http.rt.SliceRoute.<init>(com.artipie.http.rt.SliceRoute$Path[])'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$MinimalStage.thenApply(Unknown Source)
	at com.artipie.SliceFromConfig.<init>(SliceFromConfig.java:128)
	at com.artipie.http.ArtipieRepositories.lambda$resolve$1(ArtipieRepositories.java:96)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
	at io.reactivex.subjects.SingleSubject.onSuccess(SingleSubject.java:141)
	at hu.akarnokd.rxjava2.interop.SingleInterop.lambda$fromFuture$2(SingleInterop.java:82)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:60)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
	at wtf.g4s8.rio.file.ReadSubscriberState.onComplete(ReadSubscriberState.java:76)
	at wtf.g4s8.rio.file.ReadRequest$Next.process(ReadRequest.java:127)
	at wtf.g4s8.rio.file.ReadTaskQueue.run(ReadTaskQueue.java:93)
	at wtf.g4s8.rio.file.CloseChanOnError.run(CloseChanOnError.java:25)
	at wtf.g4s8.rio.file.ErrorOnException.run(ErrorOnException.java:33)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'void com.artipie.http.rt.SliceRoute.<init>(com.artipie.http.rt.SliceRoute$Path[])'
	at com.artipie.npm.http.NpmSlice.<init>(NpmSlice.java:107)
	at com.artipie.SliceFromConfig.build(SliceFromConfig.java:187)
	at com.artipie.SliceFromConfig.lambda$new$0(SliceFromConfig.java:129)
	... 27 more

[INFO] 2020-07-17 05:44:27,855 vert.x-eventloop-thread-1 com.artipie.http.DockerRoutingSlice - >> PUT /npm_repo/sample-npm-project HTTP_1_1

connection: keep-alive
user-agent: npm/6.14.6 node/v14.4.0 darwin x64
npm-in-ci: false
npm-scope:
npm-session: 7afc86cfc84eda83
referer: publish
content-type: application/json
accept: */*
content-length: 1751
accept-encoding: gzip,deflate
Host: localhost:8080
[INFO] 2020-07-17 05:44:27,870 FileStorage-2 com.artipie.http.DockerRoutingSlice - Failure: java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void com.artipie.http.rt.SliceRoute.<init>(com.artipie.http.rt.SliceRoute$Path[])'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$MinimalStage.thenApply(Unknown Source)
	at com.artipie.SliceFromConfig.<init>(SliceFromConfig.java:128)
	at com.artipie.http.ArtipieRepositories.lambda$resolve$1(ArtipieRepositories.java:96)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
	at io.reactivex.subjects.SingleSubject.onSuccess(SingleSubject.java:141)
	at hu.akarnokd.rxjava2.interop.SingleInterop.lambda$fromFuture$2(SingleInterop.java:82)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:60)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
	at wtf.g4s8.rio.file.ReadSubscriberState.onComplete(ReadSubscriberState.java:76)
	at wtf.g4s8.rio.file.ReadRequest$Next.process(ReadRequest.java:127)
	at wtf.g4s8.rio.file.ReadTaskQueue.run(ReadTaskQueue.java:93)
	at wtf.g4s8.rio.file.CloseChanOnError.run(CloseChanOnError.java:25)
	at wtf.g4s8.rio.file.ErrorOnException.run(ErrorOnException.java:33)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'void com.artipie.http.rt.SliceRoute.<init>(com.artipie.http.rt.SliceRoute$Path[])'
	at com.artipie.npm.http.NpmSlice.<init>(NpmSlice.java:107)
	at com.artipie.SliceFromConfig.build(SliceFromConfig.java:187)
	at com.artipie.SliceFromConfig.lambda$new$0(SliceFromConfig.java:129)
	... 27 more
```

The error happens when you try to publish a package to the repository:
```
$ npm publish --registry http://localhost:8080/npm_repo/
```

**Comment by olegmoz** [comment]
@Sammers21 seems that NPM has been fixed, as proofs pass

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#350` is not assigned, can't get performer
