### ISSUE TITLE
Gem: java.lang.NoSuchMethodError: 'void com.artipie.http.rt.SliceRoute.<init>(com.artipie.http.rt.SliceRoute$Path[])'

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#368]
After fixing #366, another error occured on gem push:
```
Pushing gem to http://localhost:8080/my-gem/...
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void com.artipie.http.rt.SliceRoute.<init>(com.artipie.http.rt.SliceRoute$Path[])'
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void com.artipie.http.rt.SliceRoute.<init>(com.artipie.http.rt.SliceRoute$Path[])'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$MinimalStage.thenApply(Unknown Source)
	at com.artipie.SliceFromConfig.<init>(SliceFromConfig.java:128)
	at com.artipie.http.ArtipieRepositories.lambda$resolve$1(ArtipieRepositories.java:96)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
	at io.reactivex.subjects.SingleSubject.subscribeActual(SingleSubject.java:173)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:84)
	at io.reactivex.internal.operators.single.SingleZipArray$ZipCoordinator.innerSuccess(SingleZipArray.java:119)
	at io.reactivex.internal.operators.single.SingleZipArray$ZipSingleObserver.onSuccess(SingleZipArray.java:170)
	at io.reactivex.subjects.SingleSubject.subscribeActual(SingleSubject.java:173)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleZipArray.subscribeActual(SingleZipArray.java:63)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
	at io.reactivex.Single.subscribe(Single.java:3603)
	at io.reactivex.Single.subscribe(Single.java:3589)
	at hu.akarnokd.rxjava2.interop.SingleInterop.lambda$get$0(SingleInterop.java:49)
	at io.reactivex.Single.to(Single.java:3872)
	at com.artipie.http.ArtipieRepositories.resolve(ArtipieRepositories.java:97)
	at com.artipie.http.ArtipieRepositories.lambda$slice$0(ArtipieRepositories.java:71)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(Unknown Source)
	at com.artipie.http.ArtipieRepositories.slice(ArtipieRepositories.java:67)
	at com.artipie.http.SliceByPath.response(SliceByPath.java:92)
	at com.artipie.http.rt.RtRulePath.response(RtRulePath.java:72)
	at com.artipie.http.rt.SliceRoute.lambda$response$0(SliceRoute.java:86)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at com.artipie.http.rt.SliceRoute.response(SliceRoute.java:89)
	at com.artipie.http.DockerRoutingSlice.response(DockerRoutingSlice.java:88)
	at com.artipie.http.slice.LoggingSlice.lambda$response$1(LoggingSlice.java:90)
	at com.artipie.http.SafeSlice$RsSafe.send(SafeSlice.java:98)
	at com.artipie.ResponseMetricsSlice.lambda$response$1(ResponseMetricsSlice.java:80)
	at com.artipie.vertx.VertxSliceServer.serve(VertxSliceServer.java:169)
	at com.artipie.vertx.VertxSliceServer.lambda$proxyHandler$1(VertxSliceServer.java:145)
	at io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:116)
	at io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:114)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:109)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'void com.artipie.http.rt.SliceRoute.<init>(com.artipie.http.rt.SliceRoute$Path[])'
	at com.artipie.gem.GemSlice.<init>(GemSlice.java:86)
	at com.artipie.gem.GemSlice.<init>(GemSlice.java:68)
	at com.artipie.SliceFromConfig.build(SliceFromConfig.java:195)
	at com.artipie.SliceFromConfig.lambda$new$0(SliceFromConfig.java:129)
	... 93 more
```

Looks like HTTP dependency for gem adapter should be updated

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#368` is not assigned, can't get performer
