### ISSUE TITLE
Group slice request or response body can be read twice

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#370]
When using `GroupSlice` for Maven, the reponse may be read twice and throw related exception:
```
artipie         | Content-Length: 8426
artipie         | [INFO] 2020-07-21 06:52:25,429 sdk-async-response-3-0 com.artipie.http.DockerRoutingSlice - Failure: java.util.concurrent.CompletionException: java.lang.IllegalStateException: The subscriber could not be consumed more than once. Failed on #2 attempt
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.thenCompose(Unknown Source)
artipie         | 	at com.artipie.vertx.VertxSliceServer.lambda$serve$6(VertxSliceServer.java:187)
artipie         | 	at com.artipie.ResponseMetricsSlice.lambda$response$0(ResponseMetricsSlice.java:83)
artipie         | 	at com.artipie.http.slice.LoggingSlice$LoggingConnection.accept(LoggingSlice.java:166)
artipie         | 	at com.artipie.http.group.GroupResult.replay(GroupResult.java:105)
artipie         | 	at com.artipie.http.group.GroupResults.complete(GroupResults.java:104)
artipie         | 	at com.artipie.http.group.GroupConnection.accept(GroupConnection.java:71)
artipie         | 	at com.artipie.http.rs.RsWithStatus$ConWithStatus.accept(RsWithStatus.java:109)
artipie         | 	at com.artipie.http.rs.StandardRs.lambda$static$0(StandardRs.java:41)
artipie         | 	at com.artipie.http.rs.StandardRs.send(StandardRs.java:76)
artipie         | 	at com.artipie.http.rs.RsWithStatus.send(RsWithStatus.java:70)
artipie         | 	at com.artipie.http.rs.StandardRs.send(StandardRs.java:76)
artipie         | 	at com.artipie.http.async.AsyncResponse.lambda$send$0(AsyncResponse.java:61)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
artipie         | 	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
artipie         | 	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmptySingle$SwitchIfEmptyMaybeObserver$OtherSingleObserver.onError(MaybeSwitchIfEmptySingle.java:122)
artipie         | 	at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:78)
artipie         | 	at io.reactivex.internal.operators.single.SingleError.subscribeActual(SingleError.java:42)
artipie         | 	at io.reactivex.Single.subscribe(Single.java:3603)
artipie         | 	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmptySingle$SwitchIfEmptyMaybeObserver.onComplete(MaybeSwitchIfEmptySingle.java:95)
artipie         | 	at io.reactivex.internal.operators.single.SingleFlatMapMaybe$FlatMapMaybeObserver.onComplete(SingleFlatMapMaybe.java:127)
artipie         | 	at io.reactivex.internal.operators.maybe.MaybeFlatMapSingleElement$FlatMapMaybeObserver.onComplete(MaybeFlatMapSingleElement.java:102)
artipie         | 	at io.reactivex.internal.operators.maybe.MaybeFilterSingle$FilterMaybeObserver.onSuccess(MaybeFilterSingle.java:92)
artipie         | 	at io.reactivex.subjects.SingleSubject.onSuccess(SingleSubject.java:141)
artipie         | 	at hu.akarnokd.rxjava2.interop.SingleInterop.lambda$fromFuture$2(SingleInterop.java:82)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
artipie         | 	at com.artipie.asto.s3.S3Storage.lambda$exists$0(S3Storage.java:142)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
artipie         | 	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:75)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
artipie         | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$2(AsyncApiCallTimeoutTrackingStage.java:67)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
artipie         | 	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:75)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
artipie         | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryResponseIfNeeded(AsyncRetryableStage.java:156)
artipie         | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryIfNeeded(AsyncRetryableStage.java:120)
artipie         | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.lambda$execute$0(AsyncRetryableStage.java:107)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
artipie         | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$1(MakeAsyncHttpRequestStage.java:138)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
artipie         | 	at java.base/java.lang.Thread.run(Unknown Source)
artipie         | Caused by: java.lang.IllegalStateException: The subscriber could not be consumed more than once. Failed on #2 attempt
artipie         | 	at com.artipie.asto.OneTimePublisher.subscribe(OneTimePublisher.java:77)
artipie         | 	at com.artipie.asto.Content$From.subscribe(Content.java:108)
artipie         | 	at com.artipie.asto.Content$OneTime.subscribe(Content.java:145)
artipie         | 	at com.artipie.asto.Content$From.subscribe(Content.java:108)
artipie         | 	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
artipie         | 	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
artipie         | 	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
artipie         | 	at io.reactivex.Flowable.subscribe(Flowable.
java:14918)
artipie         | 	at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:50)
artipie         | 	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
artipie         | 	at io.reactivex.internal.operators.flowable.FlowableDoOnEach.subscribeActual(FlowableDoOnEach.java:50)
artipie         | 	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
artipie         | 	at com.artipie.vertx.VertxSliceServer.lambda$serve$6(VertxSliceServer.java:186)
artipie         | 	... 63 more
artipie         | 
```

**Comment by g4s8** [comment]
Related to https://github.com/artipie/http/issues/203

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.17`

**Comment by g4s8** [comment]
@rultor release, tag=`0.8.18`

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#378](https://github.com/artipie/artipie/issues/378) is still not solved.

**Comment by g4s8** [comment]
Fixed
