### ISSUE TITLE
HTTP proxy: Max requests queued per destination 1024 exceeded for HttpDestination

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#401]
HTTP proxy starts failing after ~2 days of work with error `Max requests queued per destination 1024 exceeded for HttpDestination`:
```
artipie         | [INFO] 2020-07-29 08:57:31,272 vert.x-eventloop-thread-1 com.artipie.http.rt.SliceRoute - >> GET /g4s8/mproxy/com/artipie HTTP_1_1
artipie         | 
artipie         | Host: central.artipie.com
artipie         | X-Real-IP: x.x.x.x
artipie         | X-Forwarded-For: x.x.x.x
artipie         | Connection: close
artipie         | User-Agent: Jetty/9.4.29.v20200521
artipie         | Accept-Encoding: gzip
artipie         | Via: proxy A
artipie         | [INFO] 2020-07-29 08:57:31,290 sdk-async-response-5689-0 com.artipie.asto.s3.S3Storage - Exists 'g4s8/mproxy/com/artipie': false
artipie         | [ERROR] 2020-07-29 08:57:31,290 sdk-async-response-5689-0 com.artipie.maven.http.DownloadMavenSlice - Failed to download artifact: java.util.concurrent.RejectedExecutionException: Max requests queued per destination 1024 exceeded for HttpDestination[https://repo.maven.apache.org]@2577b370,queue=1024,pool=DuplexConnectionPool@44fedda4[c=0/64/64,a=64,i=0]
artipie         | 	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:295)
artipie         | 	at org.eclipse.jetty.client.HttpDestination.send(HttpDestination.java:265)
artipie         | 	at org.eclipse.jetty.client.HttpClient.send(HttpClient.java:595)
artipie         | 	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:772)
artipie         | 	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:764)
artipie         | 	at org.eclipse.jetty.reactive.client.internal.ResponseListenerProcessor.send(ResponseListenerProcessor.java:165)
artipie         | 	at org.eclipse.jetty.reactive.client.internal.ResponseListenerProcessor.onRequest(ResponseListenerProcessor.java:151)
artipie         | 	at org.eclipse.jetty.reactive.client.internal.AbstractSinglePublisher.request(AbstractSinglePublisher.java:84)
artipie         | 	at io.reactivex.internal.operators.flowable.FlowableSingleSingle$SingleElementSubscriber.onSubscribe(FlowableSingleSingle.java:70)
artipie         | 	at org.eclipse.jetty.reactive.client.internal.AbstractSinglePublisher.subscribe(AbstractSinglePublisher.java:56)
artipie         | 	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
artipie         | 	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
artipie         | 	at io.reactivex.internal.operators.flowable.FlowableSingleSingle.subscribeActual(FlowableSingleSingle.java:39)
artipie         | 	at io.reactivex.Single.subscribe(Single.java:3603)
artipie         | 	at io.reactivex.Single.subscribe(Single.java:3589)
artipie         | 	at hu.akarnokd.rxjava2.interop.SingleInterop.lambda$get$0(SingleInterop.java:49)
artipie         | 	at io.reactivex.Single.to(Single.java:3872)
artipie         | 	at com.artipie.maven.repository.RpRemote.lambda$artifact$2(RpRemote.java:125)
artipie         | 	at com.artipie.maven.repository.StorageCache.load(StorageCache.java:64)
artipie         | 	at com.artipie.maven.repository.RpRemote.artifact(RpRemote.java:94)
artipie         | 	at com.artipie.maven.http.DownloadMavenSlice.response(DownloadMavenSlice.java:76)
artipie         | 	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
artipie         | 	at com.artipie.http.slice.TrimPathSlice.response(TrimPathSlice.java:112)
artipie         | 	at com.artipie.http.async.AsyncSlice.lambda$response$0(AsyncSlice.java:63)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
artipie         | 	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
artipie         | 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
artipie         | 	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onSuccess(SingleDoOnSuccess.java:60)
artipie         | 	at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
artipie         | 	at wtf.g4s8.rio.file.ReadSubscriberState.onComplete(ReadSubscriberState.java:76)
artipie         | 	at wtf.g4s8.rio.file.ReadRequest$Next.process(ReadRequest.java:127)
artipie         | 	at wtf.g4s8.rio.file.ReadTaskQueue.run(ReadTaskQueue.java:93)
artipie         | 	at wtf.g4s8.rio.file.CloseChanOnError.run(CloseChanOnError.java:25)
artipie         | 	at wtf.g4s8.rio.file.ErrorOnException.run(ErrorOnException.java:33)
artipie         | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
artipie         | 	at java.base/java.lang.Thread.run(Unknown Source)
artipie         | 
```

**Comment by olegmoz** [comment]
@g4s8 this issue should be solved by proper usage of HTTP client in all adapters. I've made my part with Docker, but do not see what else should I do and I cannot verify that the issue has been fixed in production.

Could you please take the issue from me?

**Comment by g4s8** [comment]
@olegmoz thanks, I can't reproduce this issue in new version of files adapter with http-client integrated

**Comment by 0crat** [comment]
Job [#401](https://github.com/artipie/artipie/issues/401) is not in the agenda of @olegmoz[/z](https://www.0crat.com/u/olegmoz), can't set title
