### ISSUE TITLE
Github authentication error should not cause 500 error

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#406]
When using Github authentication, auth errors from Github API causes 500 error for user. We should handle authentication errors and return proper status code in that case 401.

```
artipie         | Caused by: java.lang.AssertionError: HTTP response status is not equal to 200:
artipie         | 401 Unauthorized [https://api.github.com/user]
artipie         | Server: GitHub.com
artipie         | Date: Thu, 30 Jul 2020 14:39:46 GMT
artipie         | Content-Type: application/json; charset=utf-8
artipie         | Content-Length: 83
artipie         | Status: 401 Unauthorized
artipie         | X-GitHub-Media-Type: github.v3
artipie         | X-RateLimit-Limit: 60
artipie         | X-RateLimit-Remaining: 55
artipie         | X-RateLimit-Reset: 1596123034
artipie         | Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
artipie         | Access-Control-Allow-Origin: *
artipie         | Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
artipie         | X-Frame-Options: deny
artipie         | X-Content-Type-Options: nosniff
artipie         | X-XSS-Protection: 1; mode=block
artipie         | Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
artipie         | Content-Security-Policy: default-src 'none'
artipie         | Vary: Accept-Encoding, Accept, X-Requested-With
artipie         | 
artipie         | {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
artipie         | Expected: HTTP response with status 200
artipie         |      but: was <401 Unauthorized [https://api.github.com/user]
artipie         | Server: GitHub.com
artipie         | Date: Thu, 30 Jul 2020 14:39:46 GMT
artipie         | Content-Type: application/json; charset=utf-8
artipie         | Content-Length: 83
artipie         | Status: 401 Unauthorized
artipie         | X-GitHub-Media-Type: github.v3
artipie         | X-RateLimit-Limit: 60
artipie         | X-RateLimit-Remaining: 55
artipie         | X-RateLimit-Reset: 1596123034
artipie         | Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
artipie         | Access-Control-Allow-Origin: *
artipie         | Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
artipie         | X-Frame-Options: deny
artipie         | X-Content-Type-Options: nosniff
artipie         | X-XSS-Protection: 1; mode=block
artipie         | Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
artipie         | Content-Security-Policy: default-src 'none'
artipie         | Vary: Accept-Encoding, Accept, X-Requested-With
artipie         | 
artipie         | {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}>
artipie         | 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
artipie         | 	at com.jcabi.http.response.RestResponse.assertStatus(RestResponse.java:111)
artipie         | 	at com.jcabi.github.RtJson.fetch(RtJson.java:77)
artipie         | 	at com.jcabi.github.RtUser.json(RtUser.java:166)
artipie         | 	at com.jcabi.github.RtUser.login(RtUser.java:121)
artipie         | 	at com.artipie.auth.GithubAuth.lambda$new$0(GithubAuth.java:65)
artipie         | 	at com.artipie.auth.GithubAuth.user(GithubAuth.java:86)
artipie         | 	at com.artipie.auth.ChainedAuth.user(ChainedAuth.java:74)
artipie         | 	at com.artipie.auth.LoggingAuth.user(LoggingAuth.java:68)
artipie         | 	at com.artipie.http.auth.BasicIdentities.lambda$user$3(BasicIdentities.java:67)
artipie         | 	at java.base/java.util.Optional.flatMap(Unknown Source)
artipie         | 	at com.artipie.http.auth.BasicIdentities.user(BasicIdentities.java:67)
artipie         | 	at com.artipie.http.auth.SliceAuth.response(SliceAuth.java:85)
artipie         | 	at com.artipie.http.rt.RtRulePath.response(RtRulePath.java:72)
artipie         | 	at com.artipie.http.rt.SliceRoute.lambda$response$0(SliceRoute.java:86)
artipie         | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
artipie         | 	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
artipie         | 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
artipie         | 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
artipie         | 	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
artipie         | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
artipie         | 	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
artipie         | 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
artipie         | 	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
artipie         | 	at com.artipie.http.rt.SliceRoute.response(SliceRoute.java:89)
artipie         | 	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
artipie         | 	at com.artipie.http.slice.TrimPathSlice.response(TrimPathSlice.java:112)
artipie         | 	at com.artipie.http.async.AsyncSlice.lambda$response$0(AsyncSlice.java:63)
artipie         | 	... 15 more
```

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by IlyaMoskva** [comment]
@olegmoz , please show the way of implementation. Class GithubAuth in constructor calls 3rd-party github library like this:
new RtGithub(token).users().self().login();
and method doesn't throw any exception, as implement existing interface Authentication.
What exactly is required instead of returning an empty value?
How to test that code?

**Comment by olegmoz** [comment]
@IlyaMoskva the requirement for this task is to reply with `401` instead of `500` when GitHub fails to authenticate the user. You may explore the code to see how `Authentication#user` reply is translated into an HTTP request and see how it is possible to extract error type from `new RtGithub(token).users().self().login()` invocation.

I am pretty sure that you as seasoned software engineer can find possible solutions to these problems and describe them. Then we can discuss them and find the best one together.

**Comment by dgarus** [comment]
@g4s8 hello!
Could you please review the PR?
