### ISSUE TITLE
Docker and pypi adapters are broken

### ISSUE THREAD

**Issue by Sammers21** [artipie/artipie#459]
Look like this PR(https://github.com/artipie/artipie/pull/457) broke docker and PyPI adapter

**Comment by olegmoz** [comment]
@Sammers21 could you please try to investigate and solve the issue? It seems that upgrading HTTP version has caused the problems and we have some library version conflicts

**Comment by Sammers21** [comment]
@olegmoz, sure. I will investigate.

**Comment by olegmoz** [comment]
@Sammers21 thanks

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by Sammers21** [comment]
Docker container logs during the error:
```
[INFO] 2020-08-20 10:21:08,300 FileStorage-1 com.artipie.http.rt.SliceRoute - Failure: java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'void com.artipie.http.rs.RsWithBody.<init>(com.artipie.http.Response, java.lang.String, java.nio.charset.Charset)'
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'void com.artipie.http.rs.RsWithBody.<init>(com.artipie.http.Response, java.lang.String, java.nio.charset.Charset)'
	at com.artipie.docker.http.ErrorsResponse.<init>(ErrorsResponse.java:63)
	at com.artipie.docker.http.ErrorsResponse.<init>(ErrorsResponse.java:52)
	at com.artipie.docker.http.BlobEntity$Head.lambda$response$2(BlobEntity.java:162)
	at java.base/java.util.Optional.orElseGet(Unknown Source)
	at com.artipie.docker.http.BlobEntity$Head.lambda$response$3(BlobEntity.java:161)
	... 6 more
```

Looks like HTTP version should be updated.

**Comment by Sammers21** [comment]
@olegmoz, please release a new version of docker-adapter. It will fix the problem.

**Comment by olegmoz** [comment]
@Sammers21 thanks, I have started release of docker-adapter version `0.4.3`. See https://github.com/artipie/docker-adapter/issues/299

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#459` is not assigned, can't get performer
