### ISSUE TITLE
Is the layout called `org` working?

### ISSUE THREAD

**Issue by portlek** [artipie/artipie#781]
Because I couldn't succeed in starting it.
The error:
![image](https://user-images.githubusercontent.com/12835420/100669298-3bf0fb80-336e-11eb-8b30-8030c3add73b.png)
I fixed it by changing;
```yml
# the default resource where is in the artipie-jar-with-dependencies.jar file.
credentials:
  artipie:
    pass: plain:artipie
```
to
```yml
repo:
  artipie:
    pass: plain:artipie
```
-------
```yml
permissions:
  artipie:
    - api
```
to
```yml
repo:
  artipie:
    - api
```
-------
```yml
storages:
  default:
    type: fs
    path: ./.storage/data
```
to
```yml
repo:
  default:
    type: fs
    path: ./.storage/data
```

After these changes, I started the artipie again, It's working now then, I went to `http://localhost:8080/dashboard/artipie` and I got these errors:
```
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unrecognized action api
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unrecognized action api
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:683)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:143)
	at com.artipie.http.async.AsyncSlice.response(AsyncSlice.java:63)
	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
	at com.artipie.http.rt.RtRulePath.response(RtRulePath.java:72)
	at com.artipie.http.rt.SliceRoute.lambda$response$0(SliceRoute.java:88)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at com.artipie.http.rt.SliceRoute.response(SliceRoute.java:91)
	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
	at com.artipie.http.slice.LoggingSlice.lambda$response$1(LoggingSlice.java:90)
	at com.artipie.http.TimeoutSlice$TimeoutResponse.send(TimeoutSlice.java:139)
	at com.artipie.http.SafeSlice$RsSafe.send(SafeSlice.java:98)
	at com.artipie.ResponseMetricsSlice.lambda$response$1(ResponseMetricsSlice.java:77)
	at com.artipie.http.TrafficMetricSlice$MetricsResponse.send(TrafficMetricSlice.java:102)
	at com.artipie.vertx.VertxSliceServer.serve(VertxSliceServer.java:169)
	at com.artipie.vertx.VertxSliceServer.lambda$proxyHandler$1(VertxSliceServer.java:144)
	at io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:134)
	at io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:132)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:109)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Unrecognized action api
	at com.artipie.http.auth.Action$ByString.lambda$get$2(Action.java:108)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at com.artipie.http.auth.Action$ByString.get(Action.java:106)
	at com.artipie.http.auth.Permission$ByName.<init>(Permission.java:74)
	at com.artipie.management.api.ApiAuthSlice.response(ApiAuthSlice.java:79)
	at com.artipie.http.async.AsyncSlice.lambda$response$0(AsyncSlice.java:63)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	... 69 more
```

Is there any example to explain the usage of `org` layout?
Waiting to solve: https://github.com/artipie/management-api/issues/14

**Comment by olegmoz** [comment]
@portlek we have recently released `0.13.1`, could you please try it? It should handle well non-repo configs in repo configs folder

**Comment by portlek** [comment]
> @portlek we have recently released `0.13.1`, could you please try it? It should handle well non-repo configs in repo configs folder

thanks, I'll try It ASAP.

**Comment by portlek** [comment]
getting error
![image](https://user-images.githubusercontent.com/12835420/102689047-4cc5bc00-420c-11eb-874f-130e145e7eae.png)

**Comment by olegmoz** [comment]
@portlek the error messages are expected, but the application should be fully functional. Right now there is no good way to distinguish repository config files from `_credentials`, `_permissions`, `_storages`. And we do not think that it is acceptable to prohibit `_` as first symbol of repo name or names like `_credentials`, `_permissions`, `_storages` altogether. So we made folder for repository configs customizable, so they won't mix up with other files. That is done in https://github.com/artipie/artipie/issues/804

Thank you for reporting this issue, hope it is now resolved.

**Comment by portlek** [comment]
> @portlek the error messages are expected, but the application should be fully functional. Right now there is no good way to distinguish repository config files from `_credentials`, `_permissions`, `_storages`. And we do not think that it is acceptable to prohibit `_` as first symbol of repo name or names like `_credentials`, `_permissions`, `_storages` altogether. So we made folder for repository configs customizable, so they won't mix up with other files. That is done in #804
> 
> Thank you for reporting this issue, hope it is now resolved.

Alright, thanks. I'll test the maven adapter with the org layout again.
