### ISSUE TITLE
Gem proof failing

### ISSUE THREAD

**Issue by olegmoz** [artipie/artipie#813]
Gem proof started to fail for unknown reasons without any changes to Artipie code.
Last successful run was for https://github.com/artipie/artipie/commit/783120b0ce6e20205a9165d5063f4a937d803f52 on December 15th.
It is likely that cause for the failure is some changes to environment or changes to Gem client. It does not look like Gem client version is specified in the workflow.

**Gem proof has been disabled. It should be fixed and enabled**

Gem proof is failing with the following log:
```
++ set -e
+++ pwd
+++ pwd
++ docker run --rm -d --name artipie -it -v /home/runner/work/artipie/artipie/examples/gem/artipie.yaml:/etc/artipie/artipie.yml -v /home/runner/work/artipie/artipie/examples/gem:/var/artipie -p 8080:80 artipie
d17d57e864ec13515a2c4246f783e17b60bb6813a0f31804c8fa6bbeab868668
++ sleep 5
+++ echo -n hello:world
+++ base64
++ export GEM_HOST_API_KEY=aGVsbG86d29ybGQ=
++ GEM_HOST_API_KEY=aGVsbG86d29ybGQ=
++ cd sample-project
++ gem build sample-project.gemspec
WARNING:  no files specified
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: sample-project
  Version: 1.0.0
  File: sample-project-1.0.0.gem
++ gem push sample-project-1.0.0.gem --host http://localhost:8080/my-gem
Enter your http://localhost:8080/my-gem credentials.
Don't have an account yet? Create one at http://localhost:8080/my-gem/sign_up

java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$MinimalStage.thenApply(Unknown Source)
	at com.artipie.http.async.AsyncSlice.response(AsyncSlice.java:63)
	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
	at com.artipie.http.async.AsyncSlice.lambda$response$0(AsyncSlice.java:63)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.artipie.http.auth.BasicIdentities.lambda$user$3(BasicIdentities.java:70)
	at java.base/java.util.Optional.flatMap(Unknown Source)
	at com.artipie.http.auth.BasicIdentities.user(BasicIdentities.java:69)
	at com.artipie.gem.ApiKeySlice.response(ApiKeySlice.java:73)
	at com.artipie.http.rt.RtRulePath.response(RtRulePath.java:72)
	at com.artipie.http.rt.SliceRoute.lambda$response$0(SliceRoute.java:88)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at com.artipie.http.rt.SliceRoute.response(SliceRoute.java:91)
	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
	at com.artipie.http.slice.TrimPathSlice.response(TrimPathSlice.java:114)
	at com.artipie.ContinueSlice.response(ContinueSlice.java:68)
	at com.artipie.http.async.AsyncSlice.lambda$response$0(AsyncSlice.java:63)
	... 13 more
```

**Comment by 0crat** [comment]
You @olegmoz[/z](https://www.0crat.com/u/olegmoz) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
