### ISSUE TITLE
java.nio.file.FileAlreadyExistsException: /etc/artipie/artipie.yml

### ISSUE THREAD

**Issue by tonyzeng007** [artipie/artipie#853]
Exception in thread "main" java.nio.file.FileAlreadyExistsException: /etc/artipie/artipie.yml
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
	at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
	at com.artipie.JavaResource.copy(JavaResource.java:80)
	at com.artipie.VertxMain.settings(VertxMain.java:165)
	at com.artipie.VertxMain.start(VertxMain.java:106)
	at com.artipie.VertxMain.main(VertxMain.java:152)

**Comment by g4s8** [comment]
@tonyzeng007 thanks for reporting, could you please provide more details, such as:
 1. operating system
 2. how do you start artipie (docker, java)?
 3. what is your configuration files?

**Comment by g4s8** [comment]
It should be fixed now

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#853](https://github.com/artipie/artipie/issues/853), since the job is not in scope anymore
