### ISSUE TITLE
java.nio.file.FileAlreadyExistsException: /etc/artipie/artipie.yml

### ISSUE THREAD

**Issue by zorcheal** [artipie/artipie#864]
1. Create /var/artipie/ directory
2. Run `docker run -d --name artipie -v /var/artipie:/var/artipie -p 8080:80  -e ARTIPIE_USER_NAME=artipie -e ARTIPIE_USER_PASS=qwerty artipie/artipie:latest`
3. After few seconds run:
```
docker logs artipie
Exception in thread "main" java.nio.file.FileAlreadyExistsException: /etc/artipie/artipie.yml
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
	at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
	at com.artipie.JavaResource.copy(JavaResource.java:80)
	at com.artipie.VertxMain.settings(VertxMain.java:165)
	at com.artipie.VertxMain.start(VertxMain.java:106)
	at com.artipie.VertxMain.main(VertxMain.java:152)
```

**Comment by g4s8** [comment]
@zorcheal thanks, #865 PR aimed to fix this problem

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
