### ISSUE TITLE
Unable to push python artifact to artipie docker

### ISSUE THREAD

**Issue by zuoqin** [artipie/artipie#866]
1. Create artipie.yml and put into artipie docker `docker cp artipie.yml artipie:/etc/artipie/artipie.yml`:
```
meta:
  metrics:
    type: log # Metrics type, for now only `log` type is supported
    interval: 5 # Publishing interval in seconds, default value is 5

```
2. Create python package dist and try to push `twine upload --repository-url http://localhost:8080/pypi/ -u artipie -p qwerty dist/*`
3. Returns an error:
```
Uploading distributions to http://localhost:8080/pypi/
Uploading volatility_zuoqin-0.0.4-py3-none-any.whl
100%|████████████████████████████████████████████████████████████████████████████████████| 10.9k/10.9k [00:00<00:00, 281kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 1 of 5
Uploading volatility_zuoqin-0.0.4-py3-none-any.whl
100%|████████████████████████████████████████████████████████████████████████████████████| 10.9k/10.9k [00:00<00:00, 478kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 2 of 5
Uploading volatility_zuoqin-0.0.4-py3-none-any.whl
100%|████████████████████████████████████████████████████████████████████████████████████| 10.9k/10.9k [00:00<00:00, 373kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 3 of 5
Uploading volatility_zuoqin-0.0.4-py3-none-any.whl
100%|████████████████████████████████████████████████████████████████████████████████████| 10.9k/10.9k [00:00<00:00, 390kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 4 of 5
Uploading volatility_zuoqin-0.0.4-py3-none-any.whl
100%|████████████████████████████████████████████████████████████████████████████████████| 10.9k/10.9k [00:00<00:00, 486kB/s]
Received "500: Internal Server Error" Package upload appears to have failed.  Retry 5 of 5
NOTE: Try --verbose to see response content.
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8080/pypi/
```
4. curl http://localhost:8080 returns empty content, there is no error to connect to docker HTTP port
5. `docker logs artipie`

```
[INFO] 2021-03-17 07:12:32,500 vert.x-eventloop-thread-1 com.artipie.http.MainSlice - >> POST /pypi/ HTTP_1_1

Host: localhost:8080
User-Agent: twine/3.1.1 pkginfo/1.5.0.1 requests/2.25.1 setuptools/53.0.0 requests-toolbelt/0.9.1 tqdm/4.47.0 CPython/3.6.9
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Type: multipart/form-data; boundary=92356c7ea5844faa85a2da06aa84e448
Content-Length: 11156
Authorization: Basic YXJ0aXBpZTpxd2VydHk=
[INFO] 2021-03-17 07:12:32,539 vert.x-eventloop-thread-1 com.artipie.http.MainSlice - Failure: java.lang.NullPointerException: Cannot invoke "com.amihaiemil.eoyaml.YamlMapping.value(com.amihaiemil.eoyaml.YamlNode)" because "this.decorated" is null
	at com.amihaiemil.eoyaml.StrictYamlMapping.value(StrictYamlMapping.java:69)
	at com.amihaiemil.eoyaml.YamlMapping.string(YamlMapping.java:147)
	at com.amihaiemil.eoyaml.YamlMapping.string(YamlMapping.java:135)
	at com.artipie.YamlStorage.storage(YamlStorage.java:68)
	at com.artipie.YamlSettings.storage(YamlSettings.java:71)
	at com.artipie.YamlSettings.repoConfigsStorage(YamlSettings.java:105)
	at com.artipie.http.ArtipieRepositories.slice(ArtipieRepositories.java:67)
	at com.artipie.http.SliceByPath.response(SliceByPath.java:72)
	at com.artipie.http.DockerRoutingSlice.response(DockerRoutingSlice.java:107)
	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
	at com.artipie.http.rt.RtRulePath.response(RtRulePath.java:72)
	at com.artipie.http.rt.SliceRoute.lambda$response$0(SliceRoute.java:88)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at com.artipie.http.rt.SliceRoute.response(SliceRoute.java:91)
	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
	at com.artipie.http.slice.LoggingSlice.lambda$response$1(LoggingSlice.java:90)
	at com.artipie.http.TimeoutSlice$TimeoutResponse.send(TimeoutSlice.java:139)
	at com.artipie.http.SafeSlice$RsSafe.send(SafeSlice.java:98)
	at com.artipie.ResponseMetricsSlice.lambda$response$1(ResponseMetricsSlice.java:77)
	at com.artipie.http.TrafficMetricSlice$MetricsResponse.send(TrafficMetricSlice.java:102)
	at com.artipie.vertx.VertxSliceServer.serve(VertxSliceServer.java:169)
	at com.artipie.vertx.VertxSliceServer.lambda$proxyHandler$1(VertxSliceServer.java:144)
	at io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:134)
	at io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:132)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:109)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)

[ERROR] 2021-03-17 07:12:32,541 vert.x-eventloop-thread-1 com.artipie.http.SafeSlice$RsSafe - Failed to send request to connection: java.lang.NullPointerException: Cannot invoke "com.amihaiemil.eoyaml.YamlMapping.value(com.amihaiemil.eoyaml.YamlNode)" because "this.decorated" is null
	at com.amihaiemil.eoyaml.StrictYamlMapping.value(StrictYamlMapping.java:69)
	at com.amihaiemil.eoyaml.YamlMapping.string(YamlMapping.java:147)
	at com.amihaiemil.eoyaml.YamlMapping.string(YamlMapping.java:135)
	at com.artipie.YamlStorage.storage(YamlStorage.java:68)
	at com.artipie.YamlSettings.storage(YamlSettings.java:71)
	at com.artipie.YamlSettings.repoConfigsStorage(YamlSettings.java:105)
	at com.artipie.http.ArtipieRepositories.slice(ArtipieRepositories.java:67)
	at com.artipie.http.SliceByPath.response(SliceByPath.java:72)
	at com.artipie.http.DockerRoutingSlice.response(DockerRoutingSlice.java:107)
	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
	at com.artipie.http.rt.RtRulePath.response(RtRulePath.java:72)
	at com.artipie.http.rt.SliceRoute.lambda$response$0(SliceRoute.java:88)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at com.artipie.http.rt.SliceRoute.response(SliceRoute.java:91)
	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
	at com.artipie.http.slice.LoggingSlice.lambda$response$1(LoggingSlice.java:90)
	at com.artipie.http.TimeoutSlice$TimeoutResponse.send(TimeoutSlice.java:139)
	at com.artipie.http.SafeSlice$RsSafe.send(SafeSlice.java:98)
	at com.artipie.ResponseMetricsSlice.lambda$response$1(ResponseMetricsSlice.java:77)
	at com.artipie.http.TrafficMetricSlice$MetricsResponse.send(TrafficMetricSlice.java:102)
	at com.artipie.vertx.VertxSliceServer.serve(VertxSliceServer.java:169)
	at com.artipie.vertx.VertxSliceServer.lambda$proxyHandler$1(VertxSliceServer.java:144)
	at io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:134)
	at io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:132)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:109)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)

[INFO] 2021-03-17 07:12:32,655 vert.x-eventloop-thread-1 com.artipie.http.MainSlice - >> POST /pypi/ HTTP_1_1

Host: localhost:8080
User-Agent: twine/3.1.1 pkginfo/1.5.0.1 requests/2.25.1 setuptools/53.0.0 requests-toolbelt/0.9.1 tqdm/4.47.0 CPython/3.6.9
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Type: multipart/form-data; boundary=a7d01e719b2b418094dfcbd8de79a790
Content-Length: 11156
Authorization: Basic YXJ0aXBpZTpxd2VydHk=
[INFO] 2021-03-17 07:12:32,665 vert.x-eventloop-thread-1 com.artipie.http.MainSlice - Failure: java.lang.NullPointerException: Cannot invoke "com.amihaiemil.eoyaml.YamlMapping.value(com.amihaiemil.eoyaml.YamlNode)" because "this.decorated" is null
	at com.amihaiemil.eoyaml.StrictYamlMapping.value(StrictYamlMapping.java:69)
	at com.amihaiemil.eoyaml.YamlMapping.string(YamlMapping.java:147)
	at com.amihaiemil.eoyaml.YamlMapping.string(YamlMapping.java:135)
	at com.artipie.YamlStorage.storage(YamlStorage.java:68)
	at com.artipie.YamlSettings.storage(YamlSettings.java:71)
	at com.artipie.YamlSettings.repoConfigsStorage(YamlSettings.java:105)
	at com.artipie.http.ArtipieRepositories.slice(ArtipieRepositories.java:67)
	at com.artipie.http.SliceByPath.response(SliceByPath.java:72)
	at com.artipie.http.DockerRoutingSlice.response(DockerRoutingSlice.java:107)
	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
	at com.artipie.http.rt.RtRulePath.response(RtRulePath.java:72)
	at com.artipie.http.rt.SliceRoute.lambda$response$0(SliceRoute.java:88)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at com.artipie.http.rt.SliceRoute.response(SliceRoute.java:91)
	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
	at com.artipie.http.slice.LoggingSlice.lambda$response$1(LoggingSlice.java:90)
	at com.artipie.http.TimeoutSlice$TimeoutResponse.send(TimeoutSlice.java:139)
	at com.artipie.http.SafeSlice$RsSafe.send(SafeSlice.java:98)
	at com.artipie.ResponseMetricsSlice.lambda$response$1(ResponseMetricsSlice.java:77)
	at com.artipie.http.TrafficMetricSlice$MetricsResponse.send(TrafficMetricSlice.java:102)
	at com.artipie.vertx.VertxSliceServer.serve(VertxSliceServer.java:169)
	at com.artipie.vertx.VertxSliceServer.lambda$proxyHandler$1(VertxSliceServer.java:144)
	at io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:134)
	at io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:132)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)

[ERROR] 2021-03-17 07:12:32,667 vert.x-eventloop-thread-1 com.artipie.http.SafeSlice$RsSafe - Failed to send request to connection: java.lang.NullPointerException: Cannot invoke "com.amihaiemil.eoyaml.YamlMapping.value(com.amihaiemil.eoyaml.YamlNode)" because "this.decorated" is null
	at com.amihaiemil.eoyaml.StrictYamlMapping.value(StrictYamlMapping.java:69)
	at com.amihaiemil.eoyaml.YamlMapping.string(YamlMapping.java:147)
	at com.amihaiemil.eoyaml.YamlMapping.string(YamlMapping.java:135)
	at com.artipie.YamlStorage.storage(YamlStorage.java:68)
	at com.artipie.YamlSettings.storage(YamlSettings.java:71)
	at com.artipie.YamlSettings.repoConfigsStorage(YamlSettings.java:105)
	at com.artipie.http.ArtipieRepositories.slice(ArtipieRepositories.java:67)
	at com.artipie.http.SliceByPath.response(SliceByPath.java:72)
	at com.artipie.http.DockerRoutingSlice.response(DockerRoutingSlice.java:107)
	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
	at com.artipie.http.rt.RtRulePath.response(RtRulePath.java:72)
	at com.artipie.http.rt.SliceRoute.lambda$response$0(SliceRoute.java:88)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at com.artipie.http.rt.SliceRoute.response(SliceRoute.java:91)
	at com.artipie.http.Slice$Wrap.response(Slice.java:81)
	at com.artipie.http.slice.LoggingSlice.lambda$response$1(LoggingSlice.java:90)
	at com.artipie.http.TimeoutSlice$TimeoutResponse.send(TimeoutSlice.java:139)
	at com.artipie.http.SafeSlice$RsSafe.send(SafeSlice.java:98)
	at com.artipie.ResponseMetricsSlice.lambda$response$1(ResponseMetricsSlice.java:77)
	at com.artipie.http.TrafficMetricSlice$MetricsResponse.send(TrafficMetricSlice.java:102)
	at com.artipie.vertx.VertxSliceServer.serve(VertxSliceServer.java:169)
	at com.artipie.vertx.VertxSliceServer.lambda$proxyHandler$1(VertxSliceServer.java:144)
	at io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:134)
	at io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:132)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:50)
	at io.vertx.core.http.impl.WebSocketRequestHandler.handle(WebSocketRequestHandler.java:32)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:136)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)

[INFO] 2021-03-17 07:12:32,686 vert.x-eventloop-thread-1 com.artipie.http.MainSlice - >> POST /pypi/ HTTP_1_1

Host: localhost:8080
User-Agent: twine/3.1.1 pkginfo/1.5.0.1 requests/2.25.1 setuptools/53.0.0 requests-toolbelt/0.9.1 tqdm/4.47.0 CPython/3.6.9
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Type: multipart/form-data; boundary=9ab9c0d0b4da498ba3a099564121b646
Content-Length: 11156
Authorization: Basic YXJ0aXBpZTpxd2VydHk=
```

**Comment by g4s8** [comment]
Was fixed in https://github.com/artipie/artipie/commit/ef89b15c16301705c37af02c1f9aa3eff284bf9d

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#866](https://github.com/artipie/artipie/issues/866), since the job is not in scope anymore
