### ISSUE TITLE
Consequent docker run follows FileAlreadyExistsException: /var/artipie/repo/_credentials.yaml

### ISSUE THREAD

**Issue by zuoqin** [artipie/artipie#868]
1. Create local directory with the following rights:
```
ls -l /var/artipie/
total 4
drwxrwxrwx 2 2020 2021 4096 Mar 17 11:14 repo
```
2. Run `docker run  --name artipie -v /var/artipie:/var/artipie -p 8080:8080 --user=artipie:artipie artipie/artipie:0.17.1`, which fills `repo` directory:
```
ls -l /var/artipie/repo/
total 16
-rw-r--r-- 1 2021 2020 48 Mar 17 11:14 _credentials.yaml
-rw-r--r-- 1 2021 2020 34 Mar 17 11:14 _permissions.yaml
-rwxrwxrwx 1 2020 2021 71 Mar 17 10:15 pypi.yml
-rw-r--r-- 1 2021 2020 60 Mar 17 11:14 _storages.yaml
```

3. `docker stop artipie`, `docker rm artipie`
4. Run again ` docker run  --name artipie -v /var/artipie:/var/artipie -p 8080:8080 --user=artipie:artipie artipie/artipie:0.17.1` follows error:
```
[INFO] 2021-03-17 11:16:21,754 main com.artipie.JavaResource - Resource copied successfully `example/artipie.yaml` → `/etc/artipie/artipie.yml`
Exception in thread "main" java.nio.file.FileAlreadyExistsException: /var/artipie/repo/_credentials.yaml
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
	at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
	at com.artipie.JavaResource.copy(JavaResource.java:84)
	at com.artipie.VertxMain.settings(VertxMain.java:171)
	at com.artipie.VertxMain.start(VertxMain.java:106)
	at com.artipie.VertxMain.main(VertxMain.java:152)
```

**Comment by genryxy** [comment]
@g4s8 this issue could be closed as not valid anymore as it was fixed [here](https://github.com/artipie/artipie/commit/a4fe6c29526dada234cb38b8c60d075663508af2#diff-d60af2699cd046f6d4a3247907ab79eb4ee4dad659cea90280e333f78e30d7d0R216)

**Comment by 0crat** [comment]
@genryxy[/z](https://www.0crat.com/u/genryxy) resigned from [#868](https://github.com/artipie/artipie/issues/868), since the job is not in scope anymore
