### ISSUE TITLE
Smoke-tests checks always fail

### ISSUE THREAD

**Issue by baudoliver7** [artipie/artipie#995]
Two tests fail (`conda` and `rpm`) according to this output :
```console
all tests finished:
+ grep FAILED /home/runner/work/artipie/artipie/examples/results.txt
test binary - PASSED
test debian - PASSED
test docker - PASSED
test go - PASSED
test helm - PASSED
test maven - PASSED
test npm - PASSED
test nuget - PASSED
test php - PASSED
test rpm - FAILED
test conda - FAILED
```

### RPM test

Here is the output when `RPM` test fails :
```console
+ dnf -y repository-packages example install
Example Repository                              7.0 kB/s | 253  B     00:00    
Fedora 35 - x86_64                               19 MB/s |  79 MB     00:04    
Fedora 35 openh264 (From Cisco) - x86_64        3.2 kB/s | 2.5 kB     00:00    
Fedora Modular 35 - x86_64                      2.5 MB/s | 3.3 MB     00:01    
Fedora 35 - x86_64 - Updates                     12 MB/s |  27 MB     00:02    
Fedora Modular 35 - x86_64 - Updates            935 kB/s | 2.9 MB     00:03    
No package available.
Error: No packages marked for install.
+ [[ 1 == \0 ]]
+ tee -a /home/runner/work/artipie/artipie/examples/results.txt
+ echo 'test rpm - FAILED'
```

### CONDA test

Here is the output when `CONDA` test fails :
```console
java.util.concurrent.CompletionException: com.artipie.asto.ArtipieIOException: java.io.IOException: Entry path is out of storage: my-conda/./upload/linux-64/snappy-1.1.3-0.tar.bz2
java.util.concurrent.CompletionException: com.artipie.asto.ArtipieIOException: java.io.IOException: Entry path is out of storage: my-conda/./upload/linux-64/snappy-1.1.3-0.tar.bz2
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:2173)
	at com.artipie.asto.fs.FileStorage.exists(FileStorage.java:76)
	at com.artipie.asto.LoggingStorage.exists(LoggingStorage.java:54)
	at com.artipie.asto.SubStorage.exists(SubStorage.java:51)
	at com.artipie.MeasuredStorage.exists(MeasuredStorage.java:61)
	at com.artipie.conda.http.UpdateSlice.lambda$response$1(UpdateSlice.java:77)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:653)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.artipie.asto.ArtipieIOException: java.io.IOException: Entry path is out of storage: my-conda/./upload/linux-64/snappy-1.1.3-0.tar.bz2
	at com.artipie.asto.fs.FileStorage.keyPath(FileStorage.java:305)
	... 11 more
Caused by: java.io.IOException: Entry path is out of storage: my-conda/./upload/linux-64/snappy-1.1.3-0.tar.bz2
	at com.artipie.asto.ArtipieIOException.<init>(ArtipieIOException.java:59)
	... 12 more



Error:  ('Error uploading package', 500)
+ [[ 1 == \0 ]]
+ echo 'test conda - FAILED'
```

### Proposal

We can try to fix them one by one :
- [x] Fix `RPM` Test
- [x] Fix `CONDA` Test

### Cc
https://github.com/artipie/artipie/runs/5245116160?check_suite_focus=true (if always available)

**Comment by baudoliver7** [comment]
@g4s8 I updated, in description, the message error for each test that fails

**Comment by olenagerasimova** [comment]
@baudoliver7 I've released conda 0.5.3 with the fix

**Comment by baudoliver7** [comment]
@olenagerasimova Thanks.

**Comment by baudoliver7** [comment]
@olenagerasimova @g4s8 All tests passed but process exits with 1. What's wrong ?
See logs below :
```console
all tests finished:
+ cat /home/runner/work/artipie/artipie/examples/results.txt
test binary - PASSED
test debian - PASSED
test docker - PASSED
test go - PASSED
test helm - PASSED
test maven - PASSED
test npm - PASSED
test nuget - PASSED
test php - PASSED
test rpm - PASSED
test conda - PASSED
+ grep FAILED /home/runner/work/artipie/artipie/examples/results.txt
+ stop_artipie
++ docker ps --filter name=artipie -q
+ local container=8b80afd9c354
+ [[ -n 8b80afd9c354 ]]
+ log_debug 'stopping artipie container 8b80afd9c354'
+ [[ -n true ]]
DEBUG: stopping artipie container 8b80afd9c354
+ printf 'DEBUG: %s\n' 'stopping artipie container 8b80afd9c354'
+ docker stop 8b80afd9c354
8b80afd9c354
Error: Process completed with exit code 1.
```
Cc : https://github.com/artipie/artipie/runs/5316403680?check_suite_focus=true#step:6:1957
